【OJT課題 ECサイト作成】機能仕様書を作成しました
W-Nakayama-24/ojt_ecsite pull request #1
Opened 2020-01-09 03:12 UTC by W-Nakayama-24

**機能仕様書**

* [htmlプレビュー](http://htmlpreview.github.io/?https://github.com/W-Nakayama-24/ojt_ecsite/blob/develop/UseCase/UseCase_Description.html)
* [asciidocテキスト]()

2020-01-09 05:42 UTC, tamikura commented on UseCase/UseCase_Description.adoc
> +|購入日時、購入商品一覧、合計金額を表示する
合計金額は税抜きでしょうか？税込みでしょうか？（両方でしょうか？）

2020-01-09 05:44 UTC, ntabei commented on UseCase/UseCase_Description.adoc
> +|機能名称
他2つにそろえるなら「ユースケース名称」では？

2020-01-09 05:44 UTC, tamikura commented on UseCase/UseCase_Description.adoc
> +|ショップに戻るボタン
「ショップ」の定義が不明でした（商品一覧画面も購入明細画面もショップでは？）

2020-01-09 05:47 UTC, tamikura commented on UseCase/UseCase_Description.adoc
> +|* 利用者が商品一覧画面の検索フォームに入力した文字列を含む商品のみを表示する。
検索条件が不明でした
（完全一致、前方一致、部分一致。大文字・小文字を区別するのか）

2020-01-09 05:49 UTC, tamikura commented on UseCase/UseCase_Description.adoc
> +(参考画像：検索実行後の画面イメージ)
金額ですが、カンマ区切りを入れるのが一般的（\3000 → \3,000）

2020-01-09 05:49 UTC, tamikura commented on UseCase/UseCase_Description.adoc
> +|* 利用者が商品一覧画面の検索フォームに入力した文字列を含む商品のみを表示する。
検索テキストボックスの入力条件が不明でした（入力可能文字数とか）

2020-01-09 05:50 UTC, tamikura commented on UseCase/UseCase_Description.adoc
> +** [red]##すべての検索フォームに入力が無かった場合##　⇒ <<altflow_uc03,代替フロー1に移行>>
すべての検索フォームに入力が無かったら、そもそも検索ボタンを押させないほうが親切
（エラーと分かっている行為はさせない）

2020-01-09 05:53 UTC, tamikura commented on UseCase/UseCase_Description.adoc
> +|商品の名前、価格、画像を表示する
表示順が不明でした（価格順、新着順、商品名順）
表示数が不明でした（商品全て表示？）

2020-01-09 05:53 UTC, ntabei commented on UseCase/UseCase_Description.adoc
> +.. エラーメッセージ03をメッセージ領域に表示する
05では？

2020-01-09 05:56 UTC, ntabei commented on UseCase/UseCase_Description.adoc
> +|代替フロー
UC02では不正な状態を例外フローとしているのに対してこちらでは代替フローにしているのは、何か意図があるのでしょうか。

2020-01-09 05:58 UTC, ntabei commented on UseCase/UseCase_Description.adoc
> +. 検索フォームの入力内容に対応する商品のみを<<image_viewall,商品一覧画面>>の「①商品情報表示領域」に新しく表示する
検索フォームの価格と商品名の両方に入力があった場合の挙動を明記してほしい（AND検索？）。

2020-01-09 06:01 UTC, ntabei commented on UseCase/UseCase_Description.adoc
> +. 検索フォーム(価格)欄1と欄2両方に入力があるとき、欄2の入力価格が欄1の入力価格より小さい場合
ちょっと表現がわかりにくいです。「両方に入力がある」or「欄2の値<欄1の値」の場合、にも見えてしまうので、「～に入力があり、欄2の～」くらいの方が良いと思います。

2020-01-09 06:03 UTC, ntabei commented on UseCase/UseCase_Description.adoc
> +|商品の名前、価格、画像を表示する
ついでに、横に4つで固定なのでしょうか？

2020-01-09 06:06 UTC, ntabei commented on UseCase/UseCase_Description.adoc
> +|対応する商品が「選択済み」状態になる
再度クリックで選択解除はできないのでしょうか？

2020-01-09 06:10 UTC, wnakayama commented on UseCase/UseCase_Description.adoc
> +|代替フロー
代替フロー：基本フローの代わりになるステップを実行後に事後条件を満たす
例外フロー：ユースケースの実行を断念しなければならないケース 実行後に事後条件を満たさない

代替フローと例外フローの違いについて調べたときに上記の考え方を見つけ、これを参考に
UC02→不正な状態のとき購入明細画面(事後条件)に移れないようにするので例外フロー
UC03→検索の成功/失敗にかかわらず商品一覧画面にとどまるので代替フロー としました。

2020-01-09 06:45 UTC, iwanam requested changes

2020-01-09 06:45 UTC, iwanam commented on UseCase/UseCase_Description.adoc
> +. シナリオを終了する。
個人的には、シナリオを終了するを末尾に置く必要はないと思う。
例えば、途中の条件次第で終了する場合は明示すべきだけど、最後までやりきったらそりゃ終わるでしょっていう感じが

2020-01-09 06:45 UTC, iwanam commented on UseCase/UseCase_Description.adoc
> +|* ECサイトのURLを指定・アクセス
画面遷移図によると、購入画面から戻るを押しても起動されるんだよね？

2020-01-09 06:45 UTC, iwanam commented on UseCase/UseCase_Description.adoc
> +|整数を入力して検索条件を指定する
欄の役割がきまっているのだから、１，２とせずにわかりやすい名前を付けた方がいいね

2020-01-09 06:45 UTC, iwanam commented on UseCase/UseCase_Description.adoc
> +.. <<image_viewall,商品一覧画面>>から遷移せずにシナリオを終了する
決めた仕様次第なので必ずしも直す必要はないけど、こういうチェックを考えるときに重要なのは、画面だけで判断できるか、サーバに送らないと判断できないか、ということ。
もちろん画面だけで判断できるものでもサーバでチェックする手もあるのだけど、重要なのはエンジニアとして「なぜそう決めたのか」を説明できるようにしておくといいね。

2020-01-09 06:45 UTC, iwanam commented on UseCase/UseCase_Description.adoc
> +** 文字列と数字両方の入力を受け付ける
文字列と数字の関係はどうだろう？
記号は文字列にはいっている？禁止？

2020-01-14 05:04 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +** 文字列と数字両方の入力を受け付ける
>文字列と数字の関係はどうだろう？

すみません、こちらの質問の意味をもう少し伺っても良いでしょうか?

>記号は文字列にはいっている？禁止？

考慮できていませんでした。
エスケープ処理を行う記号や入力を禁止する記号を検討中です
(want要件：MySQL導入まで進められた場合に、SQL文が不正となってしまうことを防ぐため)

2020-01-14 05:11 UTC, iwanam commented on UseCase/UseCase_Description.adoc
> +** 文字列と数字両方の入力を受け付ける
一般的に文字列っていうとすべての文字(アルファベットだけでなく各国の文字や記号数字スペースなど、場合によっては制御文字も)ということになるけど、あえて数字を別に書いてあるからこの文字列は何を指していているのだろうっていう

2020-01-14 05:19 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +** 文字列と数字両方の入力を受け付ける
ありがとうございます。
ついjavaのデータ型にそれぞれ当てはめるような考え方になっていて、"数字も文字列に含まれる"という視点が持てていませんでした。
文言修正の参考にします。

2020-01-14 05:40 UTC, iwanam commented on UseCase/UseCase_Description.adoc
> +** 文字列と数字両方の入力を受け付ける
今回の件とは関係ないけど、プログラマ的には「数字」と「数値」は全然別物、というのを覚えておくといいかも

2020-01-14 06:50 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +※ 商品情報は、最大で1ページあたり12商品分表示する
表示順が不明でした（価格順、新着順、商品名順）
表示数が不明でした（商品全て表示？）

ついでに、横に4つで固定なのでしょうか？

商品情報の表示順・表示数を追記しました。
まずは12のサンプル商品データを使ったmust要件の実現を目指し、
一般的なECサイトで求められる「多くの商品を取り扱うこと」や「ページネーションを実現すること」はwant要件に回したいと思います。

2020-01-14 06:53 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +|* ECサイトのURLを指定・アクセス
その通りです。トリガーの方には書けていなかったので追加しました。
L87 `* <<image_buy,購入明細画面>>で「商品一覧へ戻る」ボタンを押下する`

2020-01-14 07:00 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +** 入力可能文字数制限：下限値欄、上限値欄ともに9文字まで
>検索条件が不明でした
>（完全一致、前方一致、部分一致。大文字・小文字を区別するのか）

「部分一致」「大文字小文字の区別は無し」と決めて、追記しました。

> 検索テキストボックスの入力条件が不明でした（入力可能文字数とか）

以下のように定めました。
商品名検索：250文字まで　(参考：Amazonのキーワード検索)
価格検索：各9文字まで  (10億円以上の商品を取り扱わない・int型のデータサイズ超過を防ぐため)

> 検索フォームの価格と商品名の両方に入力があった場合の挙動を明記してほしい（AND検索？）。

おっしゃる通りAND検索が実行される仕様にするつもりでいました。追記しました。

2020-01-14 07:03 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +|商品の名前、税込価格、税抜価格、画像を表示する
> 合計金額は税抜きでしょうか？税込みでしょうか？（両方でしょうか？）

両方表示させる予定です。明記できていなかったので修正しました。

2020-01-14 07:08 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +|ユースケース名称
> 他2つにそろえるなら「ユースケース名称」では？

修正しました。

2020-01-14 07:10 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +|全商品一覧に戻るボタン
>「ショップ」の定義が不明でした（商品一覧画面も購入明細画面もショップでは？）

このボタンからは、検索実行前の商品一覧画面に戻ってもらう予定でしたので名称を変更しました。

2020-01-14 07:12 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +(参考画像：検索実行後の画面イメージ)
画面イメージに取り入れました。

2020-01-14 07:15 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +※検索条件の指定が無いとき(すべての検索フォームに入力が無いとき)、ボタンはクリックできない
> すべての検索フォームに入力が無かったら、そもそも検索ボタンを押させないほうが親切
>（エラーと分かっている行為はさせない）

ボタン押下後のエラーメッセージの表示ではなく、こちらの方法を使おうと思います。

2020-01-14 07:18 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +※再度クリックすると選択は解除される
> 再度クリックで選択解除はできないのでしょうか？
選択解除が可能なチェックボックスとして実装します。修正しました。

2020-01-14 08:19 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +** 入力可能文字数制限：下限値欄、上限値欄ともに9文字まで
>文字列と数字の関係はどうだろう？
>記号は文字列にはいっている？禁止？

一般的に「数字も文字列に含まれる」ということで、商品名検索で受け付ける入力の内容を修正しました。

(want要件のMySQL導入まで進められた場合)不正なSQL文が生成されることを防ぐ目的でクォーテーションの入力を受け付けない仕様にしました。

2020-01-14 08:51 UTC, tamikura approved these changes

2020-01-14 09:06 UTC, iwanam approved these changes

2020-01-15 06:16 UTC, ntabei commented on UseCase/UseCase_Description.adoc
> +|代替フロー
UC03でも、入力が不正である限り事後条件は満たさないという印象です（条件が不正＝条件は未指定という解釈もありますが）。代替フローとするならば、基本フローの1に戻る方が良いかなと。

2020-01-15 06:34 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +|代替フロー
![image](https://user-images.githubusercontent.com/54921025/72410687-5baa2000-37ac-11ea-8928-9830dce5daa4.png)

代替フローでエラーメッセージを出力した後、基本フローのステップ1に戻ることを追記しました。

2020-01-15 07:11 UTC, ntabei approved these changes

2020-01-16 00:52 UTC, W-Nakayama-24 commented
商品データが0件だった場合に表示する内容を追記しました。

![image](https://user-images.githubusercontent.com/54921025/72483836-b3e13080-3845-11ea-8cb0-3bd2035f9d2d.png)

![image](https://user-images.githubusercontent.com/54921025/72483894-decb8480-3845-11ea-9860-114eae30e947.png)

2020-01-16 02:12 UTC, merged