【OJT課題 ECサイト作成】クライアント側 ソースコード UC02[商品を購入する]部分
W-Nakayama-24/ojt_ecsite pull request #10
Opened 2020-02-19 05:52 UTC by W-Nakayama-24

2020-02-20 03:15 UTC, tatsuyaagawa commented on client/index.js
> +        .done(function (data) {
```
エラーメッセージ02

購入に失敗しました
(選択した商品の在庫がありません)
```
の場合は仕様に書いてあるけど実装上はないですかね？

2020-02-20 03:15 UTC, tatsuyaagawa commented on client/index.js
> +function sendpost(checked) {
関数名をもう少しわかりやすくしてほしいです

2020-02-20 03:16 UTC, tatsuyaagawa commented on client/index.js
> +        .done(function (data) {
あ、(want)か

2020-02-20 03:16 UTC, tatsuyaagawa commented on client/index.js
> +            sendpost(checked);
複数チェック入ってた時ってどんな動きになりますか？

2020-02-20 04:00 UTC, W-Nakayama-24 commented on client/index.js
>          {
> 関数名をもう少しわかりやすくしてほしいです

関数名sendget, sendpostを修正しました。
無名関数で書いていた部分にも命名を追加しました。

2020-02-20 04:11 UTC, W-Nakayama-24 commented on client/index.js
> +            sendpost(checked);
```
var selectedId = $('.checkbox:selectedId').map(function () {
    return $(this).val();
}).get();
```
チェックボックスの値(productID)を、mapメソッドを含んだ上記のコード(L63~65)で配列として取得していて、これはチェックした商品が1つでも複数でも同様です。
購入リクエストのあった商品のproductIDが複数格納された配列をサーバ側にPOSTで送って、全商品データと照らし合わせてもらう形をとっています

2020-02-20 04:42 UTC, W-Nakayama-24 commented on client/index.js
> +        var selectedId = $('.checkbox:checked').map(function () {
[memo]
Ctrl+F2 で複数箇所まとめて変数名を変えていたら、チェックボックスの状態指定までcheckedから書き換えてしまい文法エラー(Unrecognized Expression)になっていた

2020-02-20 05:51 UTC, iwanam requested changes

2020-02-20 05:51 UTC, iwanam commented on client/index.html
> +        <input type="submit" class="buy" value="購入へ進む" style="background-color:orange; color: #fff;"></input>
何で変えたかって説明できる？

2020-02-20 05:51 UTC, iwanam commented on client/index.html
> +        <input type="submit" class="buy" value="購入へ進む" style="background-color:orange; color: #fff;"></input>
あと実は、inputタグは閉じないのが昔ながらの習わしなんだけど、html5からはOKになったらしいね。

2020-02-20 05:51 UTC, iwanam commented on client/index.js
> +    'mouseover', '.productName', function displayFullProductName() {
この関数に名前つける意味あるかな？

2020-02-20 05:51 UTC, iwanam commented on client/index.js
> +        var selectedId = $('.checkbox:checked').map(function () {
このあたりは好き好きではあるけど、複数前提のものはそれと分かるように書いた方がいいね。特にJavaだとIDEで型が見れるけど、JSだとぱっと見わからないしね

2020-02-20 05:51 UTC, iwanam commented on client/index.js
> +        .done(function (data) {
ドットは前のオブジェクトの持ち物だというのを表しているので離さないほうがいいね

2020-02-20 05:51 UTC, iwanam commented on client/purchase.js
> +    const purchasedProduct = receipt['purchasedProductList'] || {};
constは新しいJSの書き方なんだけど、その場合はvarじゃなくletを使うというのもある。
varもゆるされているから何も問題ないんだけどね

2020-02-20 05:51 UTC, iwanam commented on client/purchase.js
> +    price = price || {};
priceってObjectなの？

2020-02-20 06:09 UTC, W-Nakayama-24 commented on client/index.html
> +        <input type="submit" class="buy" value="購入へ進む" style="background-color:orange; color: #fff;"></input>
チェックボックスの値をサーバ側に送信(submit)することを目的に<input type ="submit">を採用していたのですが、
追って調べてみたところbuttonタグの初期値もtype="submit"であり、同様の処理が可能であることに気付きました。

それこそ閉じタグが必要かどうかの違いもあって、buttonタグは子要素を持ったりformタグで括ったりできる分(レガシーな環境でない限りは)柔軟な表示/動作が実現できるようですね

今回はどちらを採用しても大きな変化は無いと考えますが、今後は要件に応じて使い分けられるよう吟味したいと思います。

2020-02-20 06:30 UTC, wnakayama commented on client/index.js
> +    'mouseover', '.productName', function displayFullProductName() {
無名関数に戻しました。 https://github.com/W-Nakayama-24/ojt_ecsite/pull/10/commits/0c58daaf9537549b9f861df6d2a3da06d448d46e

関数のうち、"引数に指定している"などの理由でその命名を用いて呼び出す機会が無いものについては、このように無名関数にしておくことで
命名の負担を減らしたり、似た命名の乱立を防ぐのが望ましいという認識でよいでしょうか??

2020-02-20 06:39 UTC, iwanam commented on client/index.js
> +    'mouseover', '.productName', function displayFullProductName() {
いやここで定義した関数って使い捨てだと思う。mouseoverされたら何をすればいいですか？という意味でのパラメータで、こういう処理してねというのをfunctionを定義して伝えているだけなので、名前つけても呼び出せないと思うんだけどどうだろう。逆にちゃんと関数定義して引数に渡してもよくて、この場合は関数定義しているから他からも呼び出せると思う
`function doSomething() {};`
`...on(xx,yy, doSomething)`

2020-02-20 07:47 UTC, W-Nakayama-24 commented on client/index.js
> +    'mouseover', '.productName', function displayFullProductName() {
確かにonメソッドの外から呼び出せませんでした。
これは即時関数というものに含まれるのでしょうか、const,let,varを使い分ける事と同様にブロックスコープを作る手段として機能していると理解しました。

名前をつける意味が薄いことは分かりましたが、逆に無名関数であることのメリットが理解しきれていないと思うのでまた後ほど質問させてください

![image](https://user-images.githubusercontent.com/54921025/74911144-5e2d1480-53ff-11ea-9494-69d70185ff12.png)

2020-02-20 07:52 UTC, W-Nakayama-24 commented
>このあたりは好き好きではあるけど、複数前提のものはそれと分かるように書いた方がいいね。特にJavaだとIDEで型が見れるけど、JSだとぱっと見わからないしね

selectedId → selectedIdArray に変更しました。
https://github.com/W-Nakayama-24/ojt_ecsite/pull/10/commits/668053b65ec7707ca3eb7c46ca1e992faa42f323
https://github.com/W-Nakayama-24/ojt_ecsite/pull/10/commits/3349d4bec79ff758b5a60a071e842a7d72f0f423
　
>ドットは前のオブジェクトの持ち物だというのを表しているので離さないほうがいいね

修正しました。

>priceってObjectなの？

短絡演算の右辺を、空Object{}からNumber 0に修正しました。 https://github.com/W-Nakayama-24/ojt_ecsite/pull/10/commits/d7f7029c798b383502dd57a78c03ec8b7a3060ec

2020-02-20 08:31 UTC, iwanam commented on client/index.js
> +    'mouseover', '.productName', function displayFullProductName() {
即時実行関数はその名の通り実行するので違うね。
```
処理A
var x=a+b;
xを使って処理B
xを使って処理C
処理D
```
みたいなとき、処理Dのあとでもxにアクセスできちゃうけど、↓みたいにすると処理Dのあとでxにはアクセスできない（変数のスコープ局所化）
処理自体は↑と同じでA,B,C,Dの順番で実行される
```
処理A
(function(){
  var x=a+b;
  xを使って処理B
  xを使って処理C
}())
処理D
```

2020-02-20 08:49 UTC, iwanam commented on client/index.js
> +    'mouseover', '.productName', function displayFullProductName() {
無名関数は1か所でしか使わないことが分かっているときに定義したりする。
今回で言えば、マウスオーバーのときにパラメータとしてfuncitonを要求されているので作るけど、マウスオーバー専用の関数を広く定義したところでそれ以降登場機会ないよね。
別に全部名前アリにしてもいいと思う。ただ知っての通り命名って色々大変なうえにツッコミどころにもなっ。とはいえ長いコードを無名で書くと見づらくなるので注意が必要

2020-02-21 00:12 UTC, W-Nakayama-24 commented on client/index.js
> +    'mouseover', '.productName', function displayFullProductName() {
ありがとうございます。
確かに今回で言うとマウスオーバー時の処理と購入ボタン押下時の処理はそれぞれ1箇所でしか登場せず、他から呼び出す必要も無いので無名関数として定義する意味が出てきますね

即時実行関数と混同していた部分も解消できたと思います。

2020-02-21 02:15 UTC, skashiyama approved these changes

2020-02-21 02:29 UTC, iwanam approved these changes

2020-02-21 03:47 UTC, tatsuyaagawa approved these changes

2020-02-21 03:51 UTC, merged