UC03商品を検索する first commit
W-Nakayama-24/ojt_ecsite pull request #13
Opened 2020-02-26 03:48 UTC by W-Nakayama-24

2020-02-27 04:27 UTC, W-Nakayama-24 commented
サーブレットに担わせている役割が少し重すぎるでしょうか。。。
UC02と同様に、結果の返却に必要なビジネスロジックは別クラスに分離させて
サーブレットの役割をリクエスト取得/セッションオブジェクト取得/JSON返却に絞ろうかと考えています

[参考] UC02 商品を購入するクラス

購入明細メーカー(ReceiptMakerクラス)からビジネスロジックを持った各クラスのメソッドを呼び出す形になっていて、サーブレットの仕事はリクエスト、レスポンス、（ReceiptMakerクラスの呼び出し、JSON変換）に絞っている

![ECサイト_UC02商品を購入する](https://user-images.githubusercontent.com/54921025/75411991-78697400-5964-11ea-9047-1f39757ac6e1.png)

2020-02-28 02:04 UTC, W-Nakayama-24 commented
![image](https://user-images.githubusercontent.com/54921025/75503804-11a69200-5a1a-11ea-938d-11f3c08e7f3c.png)

![image](https://user-images.githubusercontent.com/54921025/75503821-1bc89080-5a1a-11ea-9579-163b5788b991.png)

2020-02-28 06:44 UTC, SaitohYuusuke approved these changes

2020-03-02 05:19 UTC, iwanam requested changes
- 少なくとも一つのフォームに、という書き方はココの登場人物にいないのでやめた方がいいかな
  - もし画面とサーバで分業していると、サーバの人はフォームなんて意識してないし場合によっては知らないかもしれない
- クラス図からするとCheckResultは1つしか返らないみたいだけど、これだとチェックの順番がわからないね
  - 例えば、クォーテーションが含まれていて上限＜下限とか、クォーテーションが入っていて文字数大きいとか、何が返るか
- チェックのときに検索条件クラスを渡した方がいいかも
  - もし条件が増えたら、検索メソッドの口は変更なしでもチェックメソッドに変更が必要になる・・
- INVALIDのとこはどうやって判定する？
  - caseで分ける？
  - エラーIDがあるならメッセージは渡さなくてもいいんじゃない？
     - サーバは別にエラーメッセージを知らなくても問題ない

2020-03-02 05:33 UTC, iwanam commented
あ、ちなみにサーバはエラーメッセージを知らなくていいっていうのは、画面側に持てってことじゃなくて、せっかくエラークラスがあるのにエラーメッセージを関係ないクラスがエラークラスに教えてあげるって流れはおかしいんじゃない？ってことで

2020-03-02 06:04 UTC, W-Nakayama-24 commented
>少なくとも一つのフォームに、という書き方はココの登場人物にいないのでやめた方がいいかな

確かにサーバ側の実装ではフォームは出てこないですね、後ほど表現を変えておこうと思います。

>クラス図からするとCheckResultは1つしか返らないみたいだけど、これだとチェックの順番がわからないね

複数のバリデーション条件に違反していたときの返り値がどうなるかという観点、見落としていました。。。
実施する修正の内容を検討中です

>チェックのときに検索条件クラスを渡した方がいいかも
もし条件が増えたら、検索メソッドの口は変更なしでもチェックメソッドに変更が必要になる・・

チェックメソッドに検索条件クラスのオブジェクトではなく「商品名, 下限価格, 上限価格」の3つを渡していたのには、以下の理由がありました。
こちらも、実施する修正の内容を検討中で、疑問点がまとまり次第質問させていただくかもしれません
  - サーブレットクラスでリクエストからフォームの値を取得するときに使うgetParameterメソッドの戻り値がStringである → 下限価格・上限価格をチェックにかける際、int型にパースする必要がある → 先に検索条件クラスへセットする場合、入力チェックよりも前の段階でNumberFormatExceptionが発生する可能性がある
![image](https://user-images.githubusercontent.com/54921025/75649608-001dee00-5c97-11ea-9439-6efdd8803df7.png)

>INVALIDのとこはどうやって判定する？
caseで分ける？
エラーIDがあるならメッセージは渡さなくてもいいんじゃない？

2020-03-02 06:28 UTC, iwanam commented
>検索条件クラスのオブジェクトではなく「商品名, 下限価格, 上限価格」の3つを渡していた

なるほどね。ということは、つまりチェックメソッドはString3つを渡しているってこと？
だとすれば例えばgetParameterMapを渡して検索条件クラスを返すメソッドを用意して、その中でチェックもしてしまう、なんて手もなくはないけど、まぁ無理はしなくていいかな。

> エラーIDに応じて、エラークラスの方でメッセージを用意する

そうだね。
エラーIDとメッセージが１：１対応であるなら、両方渡す必要はないよね。
ビジネスロジックでどんなエラーが発生したかは、IDがあればきっと判別できるし

>swtich文で実装を進めている

これは直さなくてもいいけど、例えばエラーだったらIDをコンストラクタに食わせるというのは同じになるから、↓みたいになっていれば楽なのにと思ったのよね

```
if(成功){
  成功したときの処理
} else {
  new ErrorMessage(エラーID); //なんのエラーかは気にしない
} 

```

2020-03-02 07:22 UTC, W-Nakayama-24 commented
![ECサイト_クラス図_UC03商品を検索する](https://user-images.githubusercontent.com/54921025/75654005-09608800-5ca2-11ea-8100-a8c98167846e.png)
![ECサイト_UC03商品を検索する](https://user-images.githubusercontent.com/54921025/75654010-0a91b500-5ca2-11ea-9cad-5debe7ecfbc9.png)

2020-03-02 07:57 UTC, W-Nakayama-24 commented
- クラス図/シーケンス図からは入力チェックの順序が不明
  - 複数のバリデーション条件に違反していたときの返り値が不明

以上2点の問題に対応するため、
クラス図/シーケンス図の段階で実施する入力チェックの順序、バリデーションに初めて違反した時点でのエラーIDを返すことを明記します

複数のバリデーション条件に違反しているとき、違反している全ての箇所を利用者に伝えられるのがベストと考えられますが、それを実装するのはwant要件に回したいと考えています

2020-03-03 00:33 UTC, iwanam approved these changes
本当はね、チェックと検索条件は引数を合わせた方がいいのよね。同じクラスにするか別クラスにするか、同じメソッドにするか分けるかは置いといて。
あとそれぞれのkeyを合わせられるようになっているとベスト（間違えないし、使われるKeyを限定できるし）
僕の書いたものをそのまま写すと何の勉強にもならないので後学のために（もちろんもっといいやり方もあるかも）

```
doSomething() {
  if(条件をチェック(params)) {
    検索条件 = 条件オブジェクトを作る(params)
  }
}
...
private 条件をチェック(Map<String,String> params) {
  params.containsKey(CONST_KEY_A);
}
private 条件オブジェクトを作成(Map<String,String> params) {
  params.get(CONST_KEY_A);
}
```

2020-03-03 01:02 UTC, W-Nakayama-24 commented
- クラス図/シーケンス図からは入力チェックの順序が不明
  - 複数のバリデーション条件に違反していたときの返り値が不明
以上2点の問題に対応するため、
クラス図/シーケンス図の段階で実施する入力チェックの順序、バリデーションに初めて違反した時点でのエラーIDを返すことを明記します

https://github.com/W-Nakayama-24/ojt_ecsite/pull/13/commits/ffee0a708849160c5d7c6460be2409df9839b7a7

![ECサイト_UC03商品を検索する](https://user-images.githubusercontent.com/54921025/75732487-f3040c00-5d35-11ea-93ba-929624819c8c.png)

2020-03-03 06:58 UTC, merged