【OJT課題 ECサイトの作成】テストコード/ソースコード UC02[商品を検索する]部分
W-Nakayama-24/ojt_ecsite pull request #14
Opened 2020-03-03 07:21 UTC by W-Nakayama-24

2020-03-03 07:27 UTC, W-Nakayama-24 commented
![image](https://user-images.githubusercontent.com/54921025/75752299-cb2f9b00-5d6b-11ea-9419-c3b8560ec0a5.png)
![image](https://user-images.githubusercontent.com/54921025/75752313-d256a900-5d6b-11ea-9abc-72763b737cf4.png)
![image](https://user-images.githubusercontent.com/54921025/75752317-d4b90300-5d6b-11ea-83c4-842e3c19ae15.png)
![image](https://user-images.githubusercontent.com/54921025/75752324-d71b5d00-5d6b-11ea-98b5-faccdd2e4905.png)

2020-03-04 05:51 UTC, W-Nakayama-24 commented
![image](https://user-images.githubusercontent.com/54921025/75849202-a4369f00-5e27-11ea-8895-9363dbe839a9.png)

2020-03-04 07:50 UTC, tmatsumura requested changes

2020-03-04 07:50 UTC, tmatsumura commented on test/InputCheckerTest.java
> +        String[] NameArray = { "AP" };
```suggestion
        String[] nameArray = { "AP" };
```

他のテストも同様

2020-03-04 07:50 UTC, tmatsumura commented on test/InputCheckerTest.java
> +public class InputCheckerTest {
エラーが混在しているケースも確認しておいた方がいいと思います（商品名: 251文字以上 かつ 価格: 下限価格が上限価格を上回っている場合とか）
順番にチェックしてエラーのところで終了しているのでどれか1つしか返さないと思いますが、それで問題ないかと、チェックする順番は問題ないかも検討しておいたほうがいいと思います

2020-03-04 07:58 UTC, W-Nakayama-24 commented
[memo]
String[] NameArray → nameArray

2020-03-05 02:38 UTC, W-Nakayama-24 commented
https://github.com/W-Nakayama-24/ojt_ecsite/pull/14/commits/63d94dd573d1c5322f4e5b1a628b117300386f07

クライアント側の実装を並行して進めていますが、結合したプログラムを動作確認する際に単体テストでは出なかった例外が発生するようになりました。

デバッグを実施しましたが明確が原因がすぐには分からなかったため、暫定の対応としてStringUtilsの使用を取りやめ標準ライブラリを使ったnullチェック・空文字列チェックに変更しています。
入力チェック時のビジネスロジックに変更はありません。

2020-03-05 04:44 UTC, iwanam requested changes

2020-03-05 04:44 UTC, iwanam commented on src/InputChecker.java
> +        if (inputProductName.contains("'") || inputProductName.contains("\"")) {
コードだけを読むと、inputProductName=nullでinputMinPrice≠nullのとき、ぬるぽが起きるんじゃない？

2020-03-05 04:44 UTC, iwanam commented on src/SearchResultMaker.java
> +                    minPrice = Integer.parseInt(inputParameterMap.get("minPrice")[0]);
本当はこういうキーとかエラーIDは定数にしてあるのが望ましいね

2020-03-06 00:05 UTC, tatsuyaagawa commented on src/InputChecker.java
> +                    && (inputMaxPrice != null && !inputMaxPrice.isEmpty())) {
ここの条件って必要ですかね？
`int parsedMaxPrice = 1;` のところで初期値として最大値を入れておけば不要な気もします

2020-03-06 00:09 UTC, tatsuyaagawa commented on test/ErrorMessageTest.java
> +
一応deafultのパターンもお願いします

2020-03-06 00:10 UTC, tatsuyaagawa commented on src/InputChecker.java
> +        if ((inputProductName == null || inputProductName.isEmpty())
want
null かemptyの条件何回も出てくるのですが、関数自作するか、StringUtils.isEmpty()で一発でできるかも
https://qiita.com/mtanabe/items/fdfd304e461fd50e10ff

2020-03-06 00:11 UTC, tatsuyaagawa commented on src/InputChecker.java
> +        // 1以上の整数でなければエラーを返す
want
こういうコメント書いてる単位ぐらいで関数化しても良さそうです
多分その方が細かいテストもしやすくなるかなと

2020-03-06 00:59 UTC, tatsuyaagawa commented on src/InputChecker.java
> +        if ((inputProductName == null || inputProductName.isEmpty())
https://github.com/W-Nakayama-24/ojt_ecsite/pull/14#issuecomment-594998188
あ、これか・・

2020-03-06 01:02 UTC, W-Nakayama-24 commented on src/InputChecker.java
> +        if ((inputProductName == null || inputProductName.isEmpty())
やはりStringUtilsもしくは自作の関数でその都度すぐにチェックできるといいですよね。。。
この点はwant要件としてキープしました

2020-03-06 01:13 UTC, W-Nakayama-24 commented on src/InputChecker.java
> +        }
>コードだけを読むと、inputProductName=nullでinputMinPrice≠nullのとき、ぬるぽが起きるんじゃない？

null参照が行われるケースをテストの時に見落としていました。
入力チェック時に使っているローカル変数の初期化と、null/空文字列チェックの部分を修正しました。

呼び出し元のSearchResultMakerクラスでも同様の修正をしました。

2020-03-06 04:31 UTC, W-Nakayama-24 commented on test/ErrorMessageTest.java
> +
追加しました。 https://github.com/W-Nakayama-24/ojt_ecsite/pull/14/commits/1db14f423f8f892679840403eaea830977770d1a

2020-03-06 04:32 UTC, W-Nakayama-24 commented on src/SearchResultMaker.java
> +                    minPrice = Integer.parseInt(inputParameterMap.get("minPrice")[0]);
定数化しました。https://github.com/W-Nakayama-24/ojt_ecsite/pull/14/commits/c38784ac03f644f03c9d31b94fd35c6278c753fb

2020-03-06 04:33 UTC, W-Nakayama-24 commented on src/InputChecker.java
> +        if (inputProductName.contains("'") || inputProductName.contains("\"")) {
修正しました。 https://github.com/W-Nakayama-24/ojt_ecsite/pull/14#discussion_r388663763

2020-03-06 04:34 UTC, W-Nakayama-24 commented on test/InputCheckerTest.java
> +public class InputCheckerTest {
追加しました。https://github.com/W-Nakayama-24/ojt_ecsite/pull/14/commits/be760c50465e33016960f9070a79cf6e01fda36c

2020-03-06 04:41 UTC, W-Nakayama-24 commented on src/InputChecker.java
> +                    && (inputMaxPrice != null && !inputMaxPrice.isEmpty())) {
設計や機能テスト仕様を考える段階で気付けていたら良かったです…ありがとうございます。

計画した作業期間で3つのユースケースを作りきることを優先するためwant要件にさせて頂きますが、この点はぜひ改善したいと思います

2020-03-06 04:45 UTC, W-Nakayama-24 commented
頂いたレビューを踏まえた修正にともない、空文字列ではなくnullを渡すことで「検索条件指定なし」を表している際の単体テストを追加しました。

https://github.com/W-Nakayama-24/ojt_ecsite/pull/14/commits/7d052934c4e66e1dc447527fee7f5cf308e5c5db

2020-03-06 05:11 UTC, iwanam requested changes

2020-03-06 05:11 UTC, iwanam commented on src/ErrorMessage.java
> +            case 01:
定数になっておらぬ・・・

2020-03-06 05:11 UTC, iwanam commented on src/SearchResultMaker.java
> +    private static int ID_CONTAINS_QUOTATION = 05;
このあたりってなんで頭０つけてるの？

2020-03-06 05:11 UTC, iwanam commented on src/SearchResultMaker.java
> +                    maxPrice = Integer.parseInt(inputParameterMap.get(KEY_MAXPRICE)[FIRST_VALUE]);
このあたりはwantだけど、ほぼ同じ形しているからもっとわかりやすくできたかもしれないね。
↓のcaseのとこも同じ

2020-03-06 05:18 UTC, W-Nakayama-24 commented on src/ErrorMessage.java
> +            case 01:
![image](https://user-images.githubusercontent.com/54921025/76054735-fe189f80-5fb4-11ea-9579-a3650ac2d336.png)

コンパイルエラーになるのですが、定数化のやり方が間違っているのでしょうか?

2020-03-06 05:31 UTC, W-Nakayama-24 commented on src/ErrorMessage.java
> +            case 01:
![image](https://user-images.githubusercontent.com/54921025/76055405-e2ae9400-5fb6-11ea-9019-0546f5105f37.png)

ここのコンパイルエラーで定数化を諦めていたのですが、finalを付け忘れているだけでした… 修正しました。

2020-03-06 05:32 UTC, W-Nakayama-24 commented on src/SearchResultMaker.java
> +    private static int ID_CONTAINS_QUOTATION = 05;
特に理由が無かったのでエラーIDとして使用する定数を1～9の範囲に絞りました

2020-03-06 05:37 UTC, iwanam commented on src/SearchResultMaker.java
> +    private static int ID_CONTAINS_QUOTATION = 05;
うんにゃ、Javaで数値の頭に0つけると意味が変わるのよ・・・

2020-03-06 05:45 UTC, iwanam commented on src/ErrorMessage.java
> +            case 01:
これ、定数は共有しないとダメだねー。
privateでそれぞれ定義しちゃうと、たとえばエラーを追加とかコード変更されるとき、それぞれ抜け漏れなく修正しないといけないし、それらがちゃんと一致しているかっていうのを担保しないといけなくなるし

2020-03-06 05:47 UTC, iwanam commented on src/ErrorMessage.java
> +            case 01:
そのクラスでしか使わない定数と、システム全体共通で使う定数ってのがあるってことね

2020-03-06 05:49 UTC, W-Nakayama-24 commented on src/SearchResultMaker.java
> +    private static int ID_CONTAINS_QUOTATION = 05;
「java 数値 0埋め」で調べました。
コンパイルエラーにはならないものの、先頭に0を付けた数値をint型として扱おうとした場合0が削られるため望む処理,表示にならない可能性があると解釈しました
今後は文字列としての数字とデータ型に収まった数値の区別に注意したいと思います。

2020-03-06 06:20 UTC, iwanam commented on src/SearchResultMaker.java
> +    private static int ID_CONTAINS_QUOTATION = 05;
ぬーん
数値の頭に0つけると8進数になるんですよ。
今回たまたま、0が付いた数値で8,9が無かったので顕在化してないだけで(1桁の7以下は10進も8進も同じ)
0xはよく見たんじゃないかなと思うけど0はマイナーだからね。。。

2020-03-06 06:22 UTC, iwanam commented on src/SearchResultMaker.java
> +    private static int ID_CONTAINS_QUOTATION = 05;
中山君が調べてくれたのはおそらく、数字をInteger.parseIntで数値にするあたりの話だと思う

2020-03-06 06:25 UTC, W-Nakayama-24 commented on src/SearchResultMaker.java
> +    private static int ID_CONTAINS_QUOTATION = 05;
n進数からしばらく離れていてすっかり想像の範囲から抜けていました、ありがとうございます。

2020-03-06 07:26 UTC, W-Nakayama-24 commented on src/ErrorMessage.java
> +            case 01:
列挙型のErrorIdクラスを新しく作成し、ソースコード/テストコードを修正しました。
(返却するエラーメッセージを分岐させる目的のためなら、final intでも列挙型でも変わりないと判断しました)

https://github.com/W-Nakayama-24/ojt_ecsite/pull/14/commits/5bf283a0c63c1e6d8281259c2dab1f91561b3158

2020-03-06 07:29 UTC, W-Nakayama-24 commented
![image](https://user-images.githubusercontent.com/54921025/76061761-9455c100-5fc7-11ea-8df7-44982e36fe8c.png)

2020-03-06 07:48 UTC, iwanam requested changes

2020-03-06 07:48 UTC, iwanam commented on src/SearchResultMaker.java
> +    private static final String KEY_MAXPRICE = "maxPrice";
定数的にはこのあたりもだね。

2020-03-06 08:14 UTC, iwanam approved these changes

2020-03-06 08:40 UTC, tmatsumura approved these changes

2020-03-06 08:41 UTC, tatsuyaagawa approved these changes

2020-03-09 00:17 UTC, merged