first commit (client)
W-Nakayama-24/ojt_ecsite pull request #15
Opened 2020-03-05 07:01 UTC by W-Nakayama-24

2020-03-11 06:06 UTC, W-Nakayama-24 commented
![image](https://user-images.githubusercontent.com/54921025/76387276-e6bd2600-63a9-11ea-9f7f-eafe0a3ea6c3.png)

2020-03-11 07:23 UTC, W-Nakayama-24 commented
![image](https://user-images.githubusercontent.com/54921025/76392291-95fefa80-63b4-11ea-8ce2-e7127acb8950.png)

2020-03-12 02:12 UTC, W-Nakayama-24 commented
![image](https://user-images.githubusercontent.com/54921025/76480551-58e94580-6452-11ea-8dfe-37951eb118d7.png)

2020-03-12 07:44 UTC, SeigoKawamura commented on client/index.js
> +        if (!minPrice.match(/^([1-9]\d*|0)$/)) {
全角で整数が入力された時も「●検索フォーム(価格)の入力が正しくありません(整数で価格を指定してください)」で問題ないですか？
機能仕様書には特に明記してありませんでしたが、ユーザーにやさしくないと思いました。
※ サーバー側との兼ね合いもあると思いますので、どうするのが良いのか（対応するかどうかも含めて）考えてみてはどうでしょうか。

2020-03-12 07:44 UTC, SeigoKawamura commented on client/index.js
> +        const product = JSON.parse(data) || {};
dataは必ずJSON.parseできる前提ですか？そうでないならtryで囲った方が良いと思います。
それと `JSON.parse(data)` が null や 空文字になるのはどういう場合ですか？（`|| {}`の部分は必要ですか？という意図）

2020-03-13 01:56 UTC, W-Nakayama-24 commented on client/index.js
> +        if (!minPrice.match(/^([1-9]\d*|0)$/)) {
ご質問の通り、全角で整数で入力された時にもエラーメッセージを表示するようになっています。

確かに不親切な仕様ではあるので、暫定の対応として以下2点を実施しようと思います

- "半角数字の入力のみ有効である"ことを機能仕様書に追記
- クライアント側で、全角数字の入力が半角数字に適宜変換されるように実装

サーバ側に送られた価格指定も半角数字に変換出来ているとよりユーザビリティが向上しますが、こちらはwant要件実現の際に併せて実装し、評価していけたらと思います

2020-03-13 01:59 UTC, iwanam commented on client/index.js
> +            sendSearchParameter(productName, minPrice, maxPrice)
チェックと実際に使うときに引数を合わせているのはとてもいいね

2020-03-13 02:11 UTC, iwanam requested changes

2020-03-13 02:11 UTC, iwanam commented on client/index.js
> +            $('input[name="maxPrice"]').val() != "") {
JSでは!=と!==で意味が違うけど知ってるかな？

2020-03-13 02:11 UTC, iwanam commented on client/index.js
> +        message: '●すべてのフォームに入力がありませんでした 条件を指定してから検索を実行してください'
ここは何故あえてメッセージをオブジェクトに格納したか説明できる？

2020-03-13 02:11 UTC, iwanam commented on client/index.js
> +    const PRICE_MAX_DIGIT = 9;
このあたりはwantだけど、こういう定数をhtmlで使っているmaxlengthとかの値につかえると将来修正が入っても楽だし合っているかどうかなんて心配がなくなるよね

2020-03-13 02:11 UTC, iwanam commented on client/index.js
> +        return false;
そういえばmaxlengthしていされてたけど、このチェックは何のためにいれたんでしょう？

2020-03-13 02:11 UTC, iwanam commented on client/index.js
> +                }
このあたりネストも深いし、まとまった行数を１つのコメントでまとめられているってことは関数化できそうだよね。

2020-03-13 02:11 UTC, iwanam commented on client/index.js
> +                    for (var j = 0; j < cols; j++) {
人それぞれ好みなのでwantですらない点として、制御変数はただのカウンタならi,jでもいいんだけど、row,colを表すならそれに準じた名前の方が読みやすいかもね。複雑になったり長いコードになったりすると特に
例えば、 ```i * cols + j``` ってコードが下にあるけど、これがたとえば ```j * cols + i``` となっていても、実装者もレビュアも違和感を感じないかもしれないよね。だけどiがcolsに準じた名前なら気づく確率が上がるし理解もしやすくなる・・と

2020-03-13 04:55 UTC, W-Nakayama-24 commented
![image](https://user-images.githubusercontent.com/54921025/76590999-565e1d00-6532-11ea-96e6-2eaa420ce3f7.png)

2020-03-13 05:01 UTC, W-Nakayama-24 commented
![image](https://user-images.githubusercontent.com/54921025/76590999-565e1d00-6532-11ea-96e6-2eaa420ce3f7.png)

2020-03-13 05:09 UTC, W-Nakayama-24 commented on client/index.js
> +        const product = JSON.parse(data) || {};
基本的にJSON文字列がサーバから返却され、クライアント側でJSON.parseが正しく実行されることを想定していますがtry-catch文とエラーメッセージの出力で簡易的に例外処理を実装しました。

ご指摘の通りJSON.parse(data)がnullや空文字になるケースは基本的にない(※)ので || {} を削除しました

2020-03-13 05:44 UTC, W-Nakayama-24 commented on client/index.js
> +        message: '●すべてのフォームに入力がありませんでした 条件を指定してから検索を実行してください'
オブジェクトに格納する明確は理由はこのとき浮かんでいなかったです…
サーバ側の実装では最終的なレスポンスがJSONであるためエラーメッセージもキーと値を持ったオブジェクトとして返すようにしていましたが、その方式をクライアント側の実装でも用いていました。

以下の2箇所で使用する価格入力についてのエラーメッセージがまとめて変更できますが、
`$('.message').text`以降にそのままエラーメッセージを文字列で定めていても大きな問題は無く、むしろソースコードがシンプルになると考えられます

```
 if (minPrice != "") {
     if (!minPrice.match(/^([1-9]\d*|0)$/)) {
         $('.message').text(VALIDATION_ERROR.NOT_UNSIGNED_INTEGER.message);
         return false;
     }
 }
 if (maxPrice != "") {
     if (!maxPrice.match(/^([1-9]\d*|0)$/)) {
         $('.message').text(VALIDATION_ERROR.NOT_UNSIGNED_INTEGER.message);
         return false;
     }
 }
```

2020-03-13 06:40 UTC, W-Nakayama-24 commented on client/index.js
> +            $('input[name="maxPrice"]').val() != "") {
== と === の違いと同様に、オペランドだけでなく型の違いも含めて厳密に比較されるという違いを確認しています。

2020-03-13 07:44 UTC, W-Nakayama-24 commented on client/index.js
> +            if ((tmpProductIndex) < product.length) {
関数化、制御変数の改名, ロジックの見直しを実施しました。

2020-03-16 01:44 UTC, W-Nakayama-24 commented
>そういえばmaxlengthしていされてたけど、このチェックは何のためにいれたんでしょう？

必要無くなったので、削除しました。
maxlengthで入力制限を設けたほか、万が一サーバ側まで文字数制限を破った文字列が送信されたときはサーバ側で生成したエラーメッセージをクライアントに返します

>このあたりはwantだけど、こういう定数をhtmlで使っているmaxlengthとかの値につかえると将来修正が入っても楽だし合っているかどうかなんて心配がなくなるよね

上記の修正にともなってここの定数も削除しましたが、
javaScript側でinnerHTML、jQuery.html()、jQuery.text()辺りのメソッドを使って、HTMLファイルに記述していたmaxlength等の値にjavaScriptで用意した定数を使いまわせることを確認しました。

2020-03-16 02:33 UTC, iwanam requested changes

2020-03-16 02:33 UTC, iwanam commented on client/index.js
> +    const rows = (product.length) / cols;　// 行数 = 取得した商品データの件数 ÷ 列数
このロジックはおかしいよね。
現状は12件限定だったからたまたま正しく動いている感じ。

2020-03-16 02:39 UTC, W-Nakayama-24 commented on client/index.js
> +    const rows = (product.length) / cols;　// 行数 = 取得した商品データの件数 ÷ 列数
>現状は12件限定だったからたまたま正しく動いている感じ。

そうですね…先週の段階でこの事に気付き、以下の条件式を追加することで12件でなくとも正しく動く(Product配列の範囲外を参照しない)ことを確認したのですが、大元のロジックを直すべきでしょうか?

2020-03-16 05:24 UTC, iwanam commented on client/index.js
> +    const rows = (product.length) / cols;　// 行数 = 取得した商品データの件数 ÷ 列数
あー、いや４つずつしか表示できないところは今のままでとりあえずいいと思うけど、行数の計算がおかしいと思う。

2020-03-17 04:37 UTC, W-Nakayama-24 commented on client/index.js
> +            var tmpProductIndex = (tmpRow - 1) * cols + (tmpcolumn - 1);
行数と列数を実際の表示に合わせ(※)、
商品データのIDは配列のインデックスの仕様に合わせました。

(※算出時に小数点以下を切り上げて整数にする, 1から始まる, for文の条件式に用いる演算子を<=に修正)
![image](https://user-images.githubusercontent.com/54921025/76822424-4a38cf00-6854-11ea-8fe0-aae86563c198.png)

2020-03-17 07:54 UTC, iwanam requested changes

2020-03-17 07:54 UTC, iwanam commented on client/index.js
> +            if ((tmpProductIndex) < product.length) {
ちょっと聞きたいんだけど、この変数がかっこでくくられているのは何のため？
33行目もそうだけど

2020-03-17 07:54 UTC, iwanam commented on client/index.js
> +            var tmpProductIndex = (tmpRow - 1) * cols + (tmpcolumn - 1);
これは直さなくてもいいけど、もともとの指摘の意味はrowsを整数としてみたとき正しくないということだったので、このあたりを1始まりにする必要はなかったのよね。
-1が連発して読みにくくなるしね。
次に似たようなケースがあったらそのあたりも自分なりに検討してみるといいかも

2020-03-17 08:06 UTC, W-Nakayama-24 commented on client/index.js
> +            if ((tmpProductIndex) < product.length) {
```
修正前: $('.product' + (i * cols + j) + '').append

修正後 : $('.product' + (tmpProductIndex) + '').append
```
すみません、上記のようにCtrl + F2で複数個所をまとめてリファクタリングした時にカッコを消し忘れていたのをそれ以降のコーディングでも引きずっていたと思われます。
特に意図は無いので消しておきます

2020-03-17 08:08 UTC, iwanam commented on client/index.js
> +            if ((tmpProductIndex) < product.length) {
あぁ、なるほどね。謎は解けた！

2020-03-17 11:01 UTC, SeigoKawamura commented on client/index.js
> +            $('.message').text('商品データの取得に失敗しました お手数ですが開発者までご連絡ください(JSON.parseでエラー)');
お客様に向けて表示するメッセージだと思うので「JSON.parseでエラー」という文言（プログラムに関係する内容）は載せない方が良いです。
開発者までご連絡くださいと書いてあるのは大変良いです。どこかに問い合わせ先もあるとなお良いです。

2020-03-18 01:36 UTC, SeigoKawamura approved these changes

2020-03-18 01:40 UTC, iwanam approved these changes

2020-03-18 02:20 UTC, ntabei approved these changes

2020-03-18 02:31 UTC, merged