【最終課題 want要件】UC04「商品データを編集する」機能仕様
W-Nakayama-24/ojt_ecsite pull request #16
Opened 2020-03-12 06:59 UTC by W-Nakayama-24

2020-03-19 08:54 UTC, SaitohYuusuke approved these changes

2020-03-23 01:39 UTC, iwanam requested changes
1. 入力が必須であるならそれが分かるような表示がほしいね。今回は全部必須だからそれほど重要ではないけど、一般的なシステムだと必須と任意項目があるはずなので
1. 登録後一覧が表示されるのはよろしくないんじゃないかなー。もし1000番目に追加されたらわからないし、一覧画面に戻れば一覧は表示されるのよね？

2020-03-23 03:59 UTC, tmatsumura requested changes
- プレビューを見た感じでは、画面遷移図が更新されていませんでした
- 機能一覧も修正が必要だと思います
- 商品一覧画面の画像に、管理者メニューボタンがなかったです

2020-03-23 03:59 UTC, tmatsumura commented on UseCase/UseCase_Description.adoc
> +. ブラウザ上で登録ボタンを押下する
既に全く同じ商品が登録されていた場合はどうなりますか？

2020-03-23 03:59 UTC, tmatsumura commented on UseCase/UseCase_Description.adoc
> +.. エラーメッセージ06を<<image_viewall,商品一覧画面>>の「⑧メッセージ領域」に表示する
このあたり全部商品一覧画面になっていますが、商品データ管理画面ですかね？

2020-03-23 07:27 UTC, W-Nakayama-24 commented
各種変更漏れの修正と、入力必須項目の明記をしました。

「全く同じ商品が登録される場合」のフローについては現在検討中です。

2020-03-23 08:14 UTC, iwanam approved these changes
そこまで画面に注力する必要もないから今回は別にいいのだけど
画面イメージみたいな「登録しました」メッセージだと目立たな過ぎて実務だとNGではあるね。

2020-03-23 08:15 UTC, W-Nakayama-24 commented
OJT期間中にwant要件の機能を1つ作りきることを優先するため、以下の決定をしました。ご確認をお願いします。

- 商品登録後の一覧表示について、ボタン押下直後にその場で登録内容を確認できると親切かと思い実装予定でしたが 登録機能の本筋から逸れること、仕様通りに実装する手間がそこそこ掛かりそうなことを理由に一度削除しました。
 - 「まったく同じ商品を登録しようとしている」ことの検知・フロー分岐も、同様の理由で予定より早く開発が終了した場合に取り組みたいと思います。 ご指摘ありがとうございます。

2020-03-24 02:51 UTC, tmatsumura requested changes

2020-03-24 02:51 UTC, tmatsumura commented on UseCase/UseCase_Description.adoc
> +.. エラーメッセージ06を<<image_editData,商品データ管理画面>>の「⑧メッセージ領域」に表示する
```suggestion
.. エラーメッセージ06を<<image_editData,商品データ管理画面>>の「⑥メッセージ領域」に表示する
```

下の3つも同様です

2020-03-24 03:47 UTC, W-Nakayama-24 commented on UseCase/UseCase_Description.adoc
> +.. エラーメッセージ06を<<image_editData,商品データ管理画面>>の「⑧メッセージ領域」に表示する
すみません、修正しました。

2020-03-24 03:58 UTC, tmatsumura approved these changes

2020-03-24 06:26 UTC, merged