クラス図
W-Nakayama-24/ojt_ecsite pull request #3
Opened 2020-01-21 07:05 UTC by W-Nakayama-24

2020-01-21 08:41 UTC, iwanam commented
- 商品が税率を持つ必要はあるかな？
- Teamsでもちょっと言ったけど、税込み価格だけを合計すると誤差が出るよ
- アイコン的な問題かもしれないけど、商品データのjsonは1ファイルで作ってね
- 同期非同期は使い分けられている？　Productに渡しているのはどちら？
- 完全な商品一覧とは？気持ちわかるけど

2020-01-22 01:34 UTC, tmatsumura requested changes
- 商品画像のデータはどこにあって、どういうふうにブラウザに渡しますか？
- 表示する順番は価格が安い順と書いてありますが、取得した複数のProductオブジェクトを並べ替える必要はないですか？

2020-01-22 01:34 UTC, tmatsumura commented on UML/Sequence01.puml
> +ViewAllProductServlet <- Product : Productオブジェクトを返却(商品ID, 商品名, 商品カテゴリ, 税抜き価格, **税込み価格**)
レスポンスの場合は点線(`<--`)ではないですかね？
- http://www.itsenka.com/contents/development/uml/sequence.html

2020-01-22 02:00 UTC, iwanam commented
ふと思ったけど、jsonじゃなくてcsvは一つにしてね、だったわ・・・

2020-01-22 02:00 UTC, W-Nakayama-24 commented on UML/Sequence01.puml
> +ViewAllProductServlet <- Product : Productオブジェクトを返却(商品ID, 商品名, 商品カテゴリ, 税抜き価格, **税込み価格**)
忘れていました。。。
ご指摘ありがとうございます。直しておきます

2020-01-22 02:38 UTC, W-Nakayama-24 commented
> Teamsでもちょっと言ったけど、税込み価格だけを合計すると誤差が出るよ

口頭でも相談させていただきましたが、①の手法で開発しようと思います。
「税込み価格」のデータ型や「税込み価格カリキュレータ」の処理に変更が必要なため後ほどコミットします。

![image](https://user-images.githubusercontent.com/54921025/72860867-88f65100-3d0b-11ea-9d85-26e52d67786c.png)

2020-01-22 05:51 UTC, W-Nakayama-24 commented
現在のクラス図/シーケンス図を改めてこちらに掲載します。

![](https://raw.githubusercontent.com/W-Nakayama-24/ojt_ecsite/e743a2506e24a8ae11dc833dc0f5b0828ff9e59f/UML/EC%E3%82%B5%E3%82%A4%E3%83%88_%E3%82%AF%E3%83%A9%E3%82%B9%E5%9B%B3.png)

![](https://raw.githubusercontent.com/W-Nakayama-24/ojt_ecsite/e743a2506e24a8ae11dc833dc0f5b0828ff9e59f/UML/EC%E3%82%B5%E3%82%A4%E3%83%88_UC01%E5%95%86%E5%93%81%E3%82%92%E4%B8%80%E8%A6%A7%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B.png)

2020-01-22 05:53 UTC, W-Nakayama-24 commented
>商品画像のデータはどこにあって、どういうふうにブラウザに渡しますか？

以下のようなディレクトリ構造をイメージしており、画像データはimagesディレクトリの配下に置く予定です。

![image](https://user-images.githubusercontent.com/54921025/72868936-e77cf880-3d26-11ea-9d08-2cd491a7d259.png)

画像データをブラウザに表示させるまでの動きは、後ほどシーケンス図に明記します。

2020-01-22 06:25 UTC, iwanam commented
- `jsonファイル` ではないよ
- シーケンス図の矢印はメソッドを表すので、ObjectMapper.readValueはおかしい
- 自作ライブラリにJSON形式で返すメソッドはないのでは？
- Productがデータを表すクラスだとしたら、そこから処理を呼び出す？
- サイトのディレクトリ構造じゃなくて、それはEclipseの作業フォルダの構造では？
  - Webサーバに置いたものは大体見られるので、.javaを置くとマズイよね
  - 難しかったら飛ばしてもいいけど、Webアプリの配置はある程度決まっているので

2020-01-23 01:12 UTC, W-Nakayama-24 commented
>表示する順番は価格が安い順と書いてありますが、取得した複数のProductオブジェクトを並べ替える必要はないですか？

>jsonファイル ではないよ

>シーケンス図の矢印はメソッドを表すので、ObjectMapper.readValueはおかしい

>自作ライブラリにJSON形式で返すメソッドはないのでは？

>Productがデータを表すクラスだとしたら、そこから処理を呼び出す？

いただいた5点の指摘に対応しました。


以下の2点は検討中です。

>サイトのディレクトリ構造じゃなくて、それはEclipseの作業フォルダの構造では？
確かにEclipseの作業フォルダを参考にしていました。
適切なWebサイトのディレクトリ構造を一度調べておきます。

>商品画像のデータはどこにあって、どういうふうにブラウザに渡しますか？

jQueryのセレクタを使って`<p id = 'product1'></p>` や `<div class = 'image'></div>`といった箇所を指定し、画像データのURLを指定したimgタグを追加するところまではイメージしていますが、実際にjavaScriptのコーディングに移ってみないと明確にお答えしづらい状態です。

2020-01-23 01:14 UTC, W-Nakayama-24 commented
**クラス図**
![](https://raw.githubusercontent.com/W-Nakayama-24/ojt_ecsite/5db5fb9332ae0b82f68fa25fa158c957eeee44f4/UML/EC%E3%82%B5%E3%82%A4%E3%83%88_%E3%82%AF%E3%83%A9%E3%82%B9%E5%9B%B3.png)

**シーケンス図**
![](https://raw.githubusercontent.com/W-Nakayama-24/ojt_ecsite/5db5fb9332ae0b82f68fa25fa158c957eeee44f4/UML/EC%E3%82%B5%E3%82%A4%E3%83%88_UC01%E5%95%86%E5%93%81%E3%82%92%E4%B8%80%E8%A6%A7%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B.png)

2020-01-23 01:44 UTC, W-Nakayama-24 commented
質問が2点あります


![image](https://user-images.githubusercontent.com/54921025/72949991-514fdd80-3dcd-11ea-960a-54062e4fa1ad.png)

- 画像データが該当する商品データの上部に正しく表示されるためにはどうするのが適切か分からないので、ヒントを頂けると助かります。。

  初学者向けの記事や大手ECサイトのコードを見てイメージしているのは以下のいずれかの方法をとることです
  
  - 商品データの商品IDと、画像データのhtmlタグのIDを同じにして管理する

  - `<div class = "product01"></div>`を使って 
商品情報[ { 画像データ } { 商品データ (商品名,税抜き価格, 税込み価格) } ]
という構造にまとめる

- 画像データをブラウザに表示させる作業は、HTML, javaScriptのプログラミングだけで完結するという認識で合っているでしょうか?

2020-01-23 02:17 UTC, tmatsumura commented
> 画像データが該当する商品データの上部に正しく表示されるためにはどうするのが適切か分からないので、ヒントを頂けると助かります。。

画像のURLと商品の対応付けができていればどの方法でも問題ないと思います。
例えば、一番左に表示する商品の情報が分かっていれば、それに対応するURLをセットしたimgタグを追加すればできそうな気はします

> 画像データをブラウザに表示させる作業は、HTML, javaScriptのプログラミングだけで完結するという認識で合っているでしょうか?

はい、javascriptでhtmlタグを追加していくのであればjavascriptでできるんじゃないかなと思います

2020-01-23 02:32 UTC, W-Nakayama-24 commented
ディレクトリ構造を考え直しました。
 - 要素技術調査でWebアプリのサンプルを作成していたときはclassesディレクトリにjavaファイルも置いていたのですが、コンパイル後のクラスファイルのみを置くのが正しいでしょうか?

![image](https://user-images.githubusercontent.com/54921025/72951832-2a94a580-3dd3-11ea-8978-5be413c40bf7.png)

2020-01-23 07:33 UTC, tmatsumura commented on UML/Sequence01.puml
> +ViewAllProductServlet <- Product : Productオブジェクトを返却(商品ID, 商品名, 商品カテゴリ, 税抜き価格, **税込み価格**)
レスポンス以外は大丈夫ですか？同期・非同期でも線が変わると思いますが、問題なければOKです

2020-01-23 07:55 UTC, W-Nakayama-24 commented on UML/Sequence01.puml
> +ViewAllProductServlet <- Product : Productオブジェクトを返却(商品ID, 商品名, 商品カテゴリ, 税抜き価格, **税込み価格**)
ありがとうございます。
非同期通信部分のライフラインと矢印の表記を修正しました。 https://github.com/W-Nakayama-24/ojt_ecsite/pull/3/commits/91bfb5d161a5373029428e72073486380efbd3f2

![image](https://user-images.githubusercontent.com/54921025/72965795-94777400-3e00-11ea-9aa0-a4b55780299f.png)

2020-01-23 08:02 UTC, tmatsumura approved these changes

2020-01-23 08:12 UTC, iwanam approved these changes

2020-01-23 09:21 UTC, yhanba commented
参考情報ですが、
国税庁からは「一の適格請求書につき、税率ごとに１回の端数処理を行います。」
とあるので、「①単体の税込価格で切り捨てしてから足していく」という方法はダメですね。
https://www.nta.go.jp/taxes/shiraberu/zeimokubetsu/shohi/keigenzeiritsu/pdf/qa/01-09.pdf

2020-01-23 09:29 UTC, yhanba commented
機能仕様には、「商品情報は、最大で1ページあたり12商品分表示する」とあるので、
リクエストを受けた時に表示する商品を12個に絞る必要があると思うのですが、
それはどこで処理をするのでしょうか？
松村さんから商品の順番をソートする処理について指摘されているので、そこと合わせて考えれば良いと思います。
https://github.com/W-Nakayama-24/ojt_ecsite/pull/3#pullrequestreview-346300527

余裕があれば、13個目以降の商品を表示したい時の処理の流れが考えられていると良いと思います。

2020-01-23 09:32 UTC, yhanba approved these changes

2020-01-24 02:07 UTC, W-Nakayama-24 commented
>国税庁からは「一の適格請求書につき、税率ごとに１回の端数処理を行います。」
とあるので、「①単体の税込価格で切り捨てしてから足していく」という方法はダメですね。

>機能仕様には、「商品情報は、最大で1ページあたり12商品分表示する」とあるので、
リクエストを受けた時に表示する商品を12個に絞る必要があると思うのですが、
それはどこで処理をするのでしょうか？
松村さんから商品の順番をソートする処理について指摘されているので、そこと合わせて考えれば良いと思います。

>余裕があれば、13個目以降の商品を表示したい時の処理の流れが考えられていると良いと思います。

レビューありがとうございます。
今回の課題で求められるQCDとの兼ね合いを考慮して、「適格請求書等保存方式にのっとった端数処理」と「13個目以降の商品を表示したい時の処理の流れ」はmust要件を一度全て満たした後に考えようと思います。

「リクエストを受けた時に表示する商品を12個に絞る処理」については、後ほどシーケンス図にも明記します。

2020-01-24 02:14 UTC, merged