【OJT課題 ECサイト作成】テストコード UC01[商品を一覧表示する]部分
W-Nakayama-24/ojt_ecsite pull request #4
Opened 2020-01-27 04:50 UTC by W-Nakayama-24

**OJT課題 概要、機能仕様書**
以下のmarkdownファイルにまとめました。
https://github.com/W-Nakayama-24/ojt_ecsite/blob/master/README.md

**ご確認いただきたい部分**
- シーケンス図で期待している処理をテストコードに落とし込めているか
- 単体テストの段階で、他に網羅するべきテストケースは無いか

**これまでの成果物**
https://github.com/W-Nakayama-24/ojt_ecsite/pull/3/files
- クラス図 UML/ClassDiag.puml

- シーケンス図 UML/Sequence01.puml

2020-01-27 06:26 UTC, iwanam requested changes

2020-01-27 06:26 UTC, iwanam commented on test/ProductTest.java
> +     * 2つの商品データの税込み価格が同じであるとき,compareメソッドは1を返却する.
インタフェースで定義されていることについては必ず守らなければなりません。インタフェースはただメソッドの形を定義しているだけでなく、それがどういう責務を持つか、どういう値を返すか、例外を返すかについて言及されているときは必ず守りましょう。

>int compare(T o1,  T o2)
Compares its two arguments for order. Returns a negative integer, zero, or a positive integer as the first argument is less than, equal to, or greater than the second.
In the foregoing description, the notation sgn(expression) designates the mathematical signum function, which is defined to return one of -1, 0, or 1 according to whether the value of expression is negative, zero or positive.
>
>The implementor must ensure that sgn(compare(x, y)) == -sgn(compare(y, x)) for all x and y. (This implies that compare(x, y) must throw an exception if and only if compare(y, x) throws an exception.)
>
>The implementor must also ensure that the relation is transitive: ((compare(x, y)>0) && (compare(y, z)>0)) implies compare(x, z)>0.
>
>Finally, the implementor must ensure that compare(x, y)==0 implies that sgn(compare(x, z))==sgn(compare(y, z)) for all z.
>
>It is generally the case, but not strictly required that (compare(x, y)==0) == (x.equals(y)). Generally speaking, any comparator that violates this condition should clearly indicate this fact. The recommended language is "Note: this comparator imposes orderings that are inconsistent with equals."
>
>Parameters:
o1 - the first object to be compared.
o2 - the second object to be compared.
Returns:
a negative integer, zero, or a positive integer as the first argument is less than, equal to, or greater than the second.
Throws:
NullPointerException - if an argument is null and this comparator does not permit null arguments
ClassCastException - if the arguments' types prevent them from being compared by this comparator.

2020-01-27 06:26 UTC, iwanam commented on test/TaxCalculatorTest.java
> +public class TaxCalculatorTest {
例えば、categoryがnullだった場合や不正な場合、値段がマイナスの場合などに何が起こるかについてはテストしなくてもいいかな？

2020-01-27 06:26 UTC, iwanam commented on test/PriceComparatorTest.java
> +public class ProductTest {
ぱっと見、getterしかないけど、setterは大丈夫かな？

2020-01-27 06:32 UTC, W-Nakayama-24 commented on test/ProductTest.java
> +     * 2つの商品データの税込み価格が同じであるとき,compareメソッドは1を返却する.
>Finally, the implementor must ensure that compare(x, y)==0 implies that sgn(compare(x, z))==sgn(compare(y, z)) for all z.

>It is generally the case, but not strictly required that (compare(x, y)==0) == (x.equals(y)). Generally speaking, any comparator that violates this condition should clearly indicate this fact. The recommended language is "Note: this comparator imposes orderings that are inconsistent with equals."

確かに今のテストコードだとこの部分に違反していますね、後ほど修正してコミットします。

2020-01-27 06:49 UTC, W-Nakayama-24 commented on test/PriceComparatorTest.java
> +public class ProductTest {
Productインスタンスをnewした時に、setterではなくコンストラクタで商品名や価格を初期化する予定です。

want要件の実現においては「在庫管理」や「商品メンテナンス」が登場するので商品情報に変更を加えるためにsetterを使う可能性がありますが、現段階ではこのまま実装を進めようと考えています

2020-01-27 07:28 UTC, W-Nakayama-24 commented on test/PriceComparatorTest.java
> +        assertThat(compareResult, is(0));
インターフェース定義に違反していた期待結果を修正しました。
ソースコードは以下のように実装し、-1,0,1のいずれかを返すようにします。

``` 
Integer price1 = p1.getPriceIncludeTax();
Integer price2 = p2.getPriceIncludeTax();
return price1.compareTo(price2);
```

2020-01-28 02:34 UTC, W-Nakayama-24 commented on test/TaxCalculatorTest.java
> +public class TaxCalculatorTest {
- カテゴリがnullの場合
- カテゴリが空文字列の場合
- カテゴリが"飲食料品"で、値段がマイナスの場合
- カテゴリが"飲食料品"以外で、値段がマイナスの場合

以上4点のテストケースを追加しました。

この他に「想定外のカテゴリ」が入って異常が発生する可能性も指摘していただきましたが、
Stringのswitch文を使って以下のように実装し、nullを除く文字列では必ず税込み価格を算出させる予定です。

```
switch (category) {
        case "飲食料品":
            //軽減税率を適用する
        default:
            //標準税率を適用する
}
```

2020-01-28 06:36 UTC, skashiyama requested changes

2020-01-28 06:36 UTC, skashiyama commented on test/TaxCalculatorTest.java
> +        int priceWithoutTax = 1000;
```suggestion
        int priceExcludeTax = 1000;
```
include の逆なら逆の単語を使った方がいいです。

2020-01-28 09:02 UTC, iwanam approved these changes

2020-01-28 09:04 UTC, skashiyama approved these changes

2020-01-29 02:07 UTC, shujiabe commented on test/TaxCalculatorTest.java
> +        int priceExcludeTax = 1000;
テストする価格が1000だと、税率8% をかけた結果、切り捨てるのか切り上げるのかの区別がつかない。切り捨てたことが分かる価格にすべきだと思います。税率10%も同様。

2020-01-29 02:33 UTC, W-Nakayama-24 commented on test/TaxCalculatorTest.java
> +        int priceExcludeTax = 1000;
ありがとうございます。修正しました。

2020-01-29 02:33 UTC, merged