【OJT課題 ECサイト作成】ソースコード UC01[商品を一覧表示する]部分
W-Nakayama-24/ojt_ecsite pull request #5
Opened 2020-01-29 03:01 UTC by W-Nakayama-24

**OJT課題 概要、機能仕様書**
以下のmarkdownファイルにまとめました。
https://github.com/W-Nakayama-24/ojt_ecsite/blob/master/README.md

**ご確認いただきたい部分**
- シーケンス図で期待している処理をソースコードに落とし込めているか
- 修正, リファクタリングしたほうが良い箇所は無いか

**これまでの成果物**
- テストコード
https://github.com/W-Nakayama-24/ojt_ecsite/pull/4/files

　　※単体テストの実行結果, カバレッジは後ほどシングルコメントで報告します

- クラス図 UC01「商品を一覧表示する」部分まで UML/ClassDiag.puml
https://github.com/W-Nakayama-24/ojt_ecsite/pull/3/files
![](https://raw.githubusercontent.com/W-Nakayama-24/ojt_ecsite/5db5fb9332ae0b82f68fa25fa158c957eeee44f4/UML/EC%E3%82%B5%E3%82%A4%E3%83%88_%E3%82%AF%E3%83%A9%E3%82%B9%E5%9B%B3.png)

- シーケンス図　UC01「商品を一覧表示する」 UML/Sequence01.puml
https://github.com/W-Nakayama-24/ojt_ecsite/pull/3/files
![](https://raw.githubusercontent.com/W-Nakayama-24/ojt_ecsite/5db5fb9332ae0b82f68fa25fa158c957eeee44f4/UML/EC%E3%82%B5%E3%82%A4%E3%83%88_UC01%E5%95%86%E5%93%81%E3%82%92%E4%B8%80%E8%A6%A7%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B.png)

**補足事項**
- 「ViewAllProductServlet」のテスト
クライアントからのgetリクエストをトリガーとし、CSVファイルにあったデータがJSON文字列に変換できることを期待するクラスです。
単体テストの結果ではなく、各クラスを結合した後の動きを見て評価します。

- 「csvParser」のテスト
CSVファイルのデータをString型の2次元配列に変換する自作ライブラリです。
前回の課題で既にテストを実施済みのため、今回テストコードは省略しています
[CsvParser (ソースコード,テストコード)](https://github.com/W-Nakayama-24/ojt_techSurvey/pull/3/files#diff-0aa2edd5b04124152655fd870c6b094c)

2020-01-29 03:05 UTC, W-Nakayama-24 commented
**単体テストの実行結果**
コードカバレッジはいずれのクラスも100%を計測しました。

TaxCalculator

![image](https://user-images.githubusercontent.com/54921025/73324695-34188480-428f-11ea-9ca4-e2017074b717.png)

Product

![image](https://user-images.githubusercontent.com/54921025/73324714-44c8fa80-428f-11ea-88e6-010ead78e6df.png)

PriceComparator

![image](https://user-images.githubusercontent.com/54921025/73324729-527e8000-428f-11ea-94ca-76bfe8f2a7ce.png)

2020-01-29 05:18 UTC, iwanam requested changes

2020-01-29 05:18 UTC, iwanam commented on src/PriceComparator.java
> + * リスト中のすべての商品が持つ税込み価格を安い順にソートする.
他のクラスとの組み合わせを書いてしまうと他で使えなくなるのでやらない方が吉

2020-01-29 05:18 UTC, iwanam commented on src/TaxCalculator.java
> +        switch (category) {
ここでswitch文を使った理由ってある？

2020-01-29 05:18 UTC, iwanam commented on src/ViewAllProductServlet.java
> +                int priceWithoutTax = Integer.parseInt(sample2dArray[i][3]);
こんな感じのコードだと0,1,2,3が何を示すのかわからないので、定数を使う方がいいね

2020-01-29 05:18 UTC, iwanam commented on src/ViewAllProductServlet.java
> +            e.printStackTrace();
この手のprintStackTraceしかしないcatchは握りつぶし状態になるので、意図的にこうするのであれば何かコメントを入れておくといいよ。

2020-01-29 05:27 UTC, SeigoKawamura commented on src/ViewAllProductServlet.java
> +                TaxCalculator taxCalculator = new TaxCalculator();
ループの中で毎回TaxCalculatorがnewされていますが、毎回newする必要ありますか？

2020-01-29 05:27 UTC, SeigoKawamura commented on src/ViewAllProductServlet.java
> +            sample2dArray = csvParser.convertTo2dArray("c:\\csvTest\\ecData.csv");
パスは定数で定義した方が良いです

2020-01-29 05:27 UTC, SeigoKawamura commented on src/ViewAllProductServlet.java
> +            if (fromIndex < 0 || toIndex > productList.size()) {
fromIndex < 0 になるケースは存在しないので必要ないと思います

2020-01-29 05:31 UTC, W-Nakayama-24 commented on src/TaxCalculator.java
> +        switch (category) {
今は「飲食料品かそうでないか」の分岐しかありませんが、
軽減税率対象のカテゴリや適用する税率のバリエーションが増えたとき、switch文を採用していた方がコードの可読性を保てると考えました。

2020-01-29 06:38 UTC, W-Nakayama-24 commented
>他のクラスとの組み合わせを書いてしまうと他で使えなくなるのでやらない方が吉

>こんな感じのコードだと0,1,2,3が何を示すのかわからないので、定数を使う方がいいね

>ループの中で毎回TaxCalculatorがnewされていますが、毎回newする必要ありますか？

>パスは定数で定義した方が良いです

>fromIndex < 0 になるケースは存在しないので必要ないと思います

修正しました。https://github.com/W-Nakayama-24/ojt_ecsite/pull/5/commits/5279501ea8216df954ea59ae75c6fe912cd81a01

2020-01-29 06:45 UTC, W-Nakayama-24 commented on src/ViewAllProductServlet.java
> +            e.printStackTrace();
それぞれの例外のcatchブロックにコメントで補足しました。
仮に発生した場合、CSV→JSONの変換をスキップして空のJSON文字列を返すのでクライアントには商品データが0件だった場合と同じ画面表示になります。

先日アドバイス頂いた通り、開発者側のミスで0件表示になっていることが利用者にも分かるのが理想的ですが
それらはwant要件とし、現段階ではスタックトレースを使った簡易的な例外処理を実装しました。

2020-01-29 08:06 UTC, SeigoKawamura commented on src/ViewAllProductServlet.java
> +    static final int COLMUN_ID = 0;
COLUMN_ID ですかね…？

2020-01-29 08:23 UTC, SeigoKawamura approved these changes

2020-01-29 08:31 UTC, iwanam approved these changes

2020-01-30 01:36 UTC, ntabei commented on src/ViewAllProductServlet.java
> +    static final String CSVPATH = "c:\\csvTest\\ecData.csv";
この下の定数もですが、全部privateで良いのではないでしょうか

2020-01-30 01:37 UTC, ntabei commented on src/ViewAllProductServlet.java
> +        String[][] sample2dArray = null;
ここで定義する必要はない（try内で良い）ように見えます

2020-01-30 01:38 UTC, ntabei commented on src/ViewAllProductServlet.java
> +            int fromIndex = 0; // subListの下端点(これを含む)
必ず0だと思いますが、今後何かで変わることを見込んでいるのでしょうか？

2020-01-30 01:39 UTC, ntabei commented on src/ViewAllProductServlet.java
> +            int toIndex = 12; // subListの上端点(これを含まない)
1ページの上限が12件という意味であれば、12という数字は定数にしておいた方が良いと思います。

2020-01-30 02:27 UTC, W-Nakayama-24 commented
>この下の定数もですが、全部privateで良いのではないでしょうか

>ここで定義する必要はない（try内で良い）ように見えます

修正しました。 https://github.com/W-Nakayama-24/ojt_ecsite/pull/5/commits/baa5a40b34e33c08bc25209876bddfc688973995

2020-01-30 02:31 UTC, W-Nakayama-24 commented
>必ず0だと思いますが、今後何かで変わることを見込んでいるのでしょうか？

特に見込んでいなかったので、暫定の対応として定数化しました。
subListメソッドで例外を発生させまいと、公式リファレンスに書かれている条件式を機械的にプログラムへ落とし込んだのが良くなかったです

> 例外:
> IndexOutOfBoundsException - 端点のインデックス値が不正である場合
(fromIndex < 0||toIndex> size||fromIndex> toIndex)

https://docs.oracle.com/javase/jp/8/docs/api/java/util/List.html#subList-int-int-

2020-01-30 02:41 UTC, W-Nakayama-24 commented
> 1ページの上限が12件という意味であれば、12という数字は定数にしておいた方が良いと思います。

こちらも定数化しました。

1点相談させてください。
もともと以下のようなコードを書いてIndexOutOfBoundsExceptionを防止していたのですが
fromIndexとtoIndexの部分を定数化したことで代入不可となり、同じ対策が出来なくなりました。
```
if (toIndex > productList.size()) {
    // 指定するインデックス値が商品リストの範囲外である場合, 下端を0, 上端をリストのsizeに指定する
    fromIndex = 0;
    toIndex = productList.size();
}
```

この対策をすること自体にも疑問があって、
たとえば表示上限を50件とした場合もIndexOutOfBoundsExceptionを出すのではなく取得できた12件は表示してあげる方が親切だろうと考え、別のアプローチを検討中です。

自分でも調査中ですが、よく使われる手法やメソッド、その他ご提案があればコメント頂けると助かります。

2020-01-30 03:18 UTC, W-Nakayama-24 commented
>元のロジックの「」が定数ですよね？それを定数にしたら最終的にはどうなるでしょうか 
```
fromIndex = 「0」
toIndex = 「12」
if (「12」 > productList.size()) {
    toIndex = productList.size();
}
subList = productList.subList(fromIndex, toIndex);
```





![image](https://user-images.githubusercontent.com/54921025/73417099-44496600-435a-11ea-867a-5f6377a5ae23.png)


![image](https://user-images.githubusercontent.com/54921025/73417049-1cf29900-435a-11ea-853b-a0f306b20dbb.png)

![image](https://user-images.githubusercontent.com/54921025/73417061-22e87a00-435a-11ea-8f58-3c46af369e7b.png)

2020-01-30 03:22 UTC, W-Nakayama-24 commented
>この指摘は0（開始インデックス）とか12（1ページの表示数）といった意味のある数字を定数にしましょうという話で、ロジックはそのままで問題ありません。
元のロジックの「」が定数ですよね？それを定数にしたら最終的にはどうなるでしょうか 

```
fromIndex = 「0」
toIndex = 「12」
if (「12」 > productList.size()) {
    toIndex = productList.size();
}
subList = productList.subList(fromIndex, toIndex);
```


最初に変数で宣言していたfromIndex, toIndexを定数化とともに消していたので、代入が出来ずに悩んでいました。
確かにロジックの問題は無く、右辺だけ定数化していればOKでしたね。。。ありがとうございます!

![image](https://user-images.githubusercontent.com/54921025/73417260-ce91ca00-435a-11ea-881a-349bfc870ba3.png)

2020-01-30 03:49 UTC, ntabei commented on src/ViewAllProductServlet.java
> +            int toIndex = DISPLAY_PRODUCTS_LOWERLIMIT;
最初の代入が逆では

2020-01-30 03:53 UTC, W-Nakayama-24 commented on src/ViewAllProductServlet.java
> +            int toIndex = DISPLAY_PRODUCTS_LOWERLIMIT;
そそっかしいミスで申し訳ないです… 
修正しました、指摘ありがとうございます。

2020-01-30 03:59 UTC, W-Nakayama-24 commented
改めて単体テストを実施した結果を記載します

![image](https://user-images.githubusercontent.com/54921025/73418779-267eff80-4360-11ea-9b6b-32fa762e2fc5.png)
![image](https://user-images.githubusercontent.com/54921025/73418808-3860a280-4360-11ea-86c9-dbe533db0713.png)
![image](https://user-images.githubusercontent.com/54921025/73418822-48788200-4360-11ea-8f01-f6fbf54d0eb6.png)

2020-01-30 04:05 UTC, ntabei approved these changes

2020-01-30 06:59 UTC, merged