【OJT課題 ECサイト作成】クライアント側 ソースコード UC01[商品を一覧表示する]部分
W-Nakayama-24/ojt_ecsite pull request #6
Opened 2020-01-30 07:57 UTC by W-Nakayama-24

2020-01-30 08:05 UTC, W-Nakayama-24 commented on client/productData.json
> +    },
価格が安い順に並べかえた後のJSON文字列

2020-01-30 08:11 UTC, W-Nakayama-24 commented
memo
4商品ごとに改行されるイメージで表示したいが、ループ処理で上手に実現できない
↓
候補
- まずは4商品ごとに<tr>が挟めることを最優先で書いてみる
- 良い具合にテーブルを取り扱うjQueryのライブラリがあるかもしれない

2020-01-30 09:07 UTC, tatsuyaagawa commented on client/index.js
> +                // (途中)<tr></tr>で新しい列を作成　4件ごとに改行するイメージで商品データを並べたい
もうちょっと頑張ったらできそう。どうすれば意図通りのHTMLを組み立てられるか考えてみてください

あと余談ですが、javascriptは特殊で `==` と ``===` で意味が違います。時間あるときに調べてみてください。

2020-01-31 04:32 UTC, W-Nakayama-24 commented on client/index.js
> +                // (途中)<tr></tr>で新しい列を作成　4件ごとに改行するイメージで商品データを並べたい
>もうちょっと頑張ったらできそう。どうすれば意図通りのHTMLを組み立てられるか考えてみてください

ありがとうございます、何とか実現しました!

>あと余談ですが、javascriptは == と === で意味が違います。時間あるときに調べてみてください。

今朝チェックしました。頭に入れておきます

2020-02-03 06:41 UTC, W-Nakayama-24 commented on client/index.js
> +);
![image](https://user-images.githubusercontent.com/54921025/73631144-8d235680-469b-11ea-9030-e919fc614cb9.png)

2020-02-03 07:01 UTC, W-Nakayama-24 commented on client/index.html
> +    </span>
**実装**

![image](https://user-images.githubusercontent.com/54921025/73631949-be048b00-469d-11ea-951e-46588fca75c3.png)


[**機能仕様書で定めていた画面仕様**](http://htmlpreview.github.io/?https://github.com/W-Nakayama-24/ojt_ecsite/blob/develop/UseCase/UseCase_Description.html)

![image](https://user-images.githubusercontent.com/54921025/73631935-b218c900-469d-11ea-9b88-12cd0954fe1f.png)


上図のように、メッセージ領域の配置が少し異なっています。
<nobr>タグの利用や、スタイルシートでwhite-spaceプロパティをnowrapに設定する等の方法を試しましたが仕様書通りの配置が実現しませんでした。

こちら、なにかヒントやご提案があれば頂けると助かります

2020-02-03 08:12 UTC, tatsuyaagawa commented on client/index.js
> +                        j++
3つ目の変数は必要でしょうか？

2020-02-03 08:27 UTC, tatsuyaagawa commented on client/index.js
> +                        $('.test' + i + '').append('<td class="product' + j + '"></td>');
`.test` が残ってるので適切な名前をつけましょう

2020-02-03 08:29 UTC, tatsuyaagawa commented on client/index.js
> +            const product = JSON.parse(jsonstr);
この2行って両方必要でしょうか？
`const product = data || {}` とかで良さそうに見えます

2020-02-03 08:32 UTC, tatsuyaagawa commented on client/index.html
> +    </span>
すいません。もう少し詳しく教えてください
仕様書通りの配置と、実際の実装の差分がなんとなくしかわからなかったです

2020-02-03 08:48 UTC, iwanam requested changes

2020-02-03 08:48 UTC, iwanam commented on client/ecData.csv
> +1,*おいしいみず,飲食料品,100,water.png
プルリクの分け方のせいかもしれないけど、ファイルをもっているのはサーバ側です。

2020-02-03 08:48 UTC, iwanam commented on client/index.js
> +    $.get('http://10.63.8.160:8080/ojt_ecsite/ViewAllProductServlet')
これはwantでいいのだけど、システムを作っている段階でIPをハードコーディングしてしまうと評価が終わった後お客様のところへ導入するときに変更が必要になって色々アレなんです。
そもそもクライアントでhtmlが表示できるということは、サーバのことは知っているはずですね。
・・つまり

2020-02-03 08:48 UTC, iwanam commented on client/index.js
> +        console.log(checked);
レビューに出す段階では、consoleは残っていない方がいいですね。
JavaのSystem.outと同じ。
もちろん、ログを表示したいという明確なものがあれば可（実際のシステムではconsoleではないですけど、今回はLoggerとかは考えてないので）

2020-02-03 08:48 UTC, iwanam commented on client/productData.json
> +[
jsonファイルって何に使ってます？

2020-02-03 08:48 UTC, iwanam commented on client/index.js
> +            $('.message').replaceWith('<h4 class="message">' + checked.join(''));
見やすくそろえているというのはとてもいいのだけど、もしエラー用のclassがmessageじゃなくなったら変更するところは・・・と考えるとリファクタリングの余地があるかもね

2020-02-03 08:48 UTC, iwanam commented on client/index.js
> +                    $('.productInfoTable').append('<tr class ="test' + i + '">');
trってどっかで閉じてる？

2020-02-03 08:51 UTC, iwanam commented on client/ecData.csv
> +1,*おいしいみず,飲食料品,100,water.png
ディレクトリ名的な意味で

2020-02-04 00:51 UTC, W-Nakayama-24 commented
>.test が残ってるので適切な名前をつけましょう

>この2行って両方必要でしょうか？
const product = data || {} とかで良さそうに見えます

>レビューに出す段階では、consoleは残っていない方がいいですね。
JavaのSystem.outと同じ。

>trってどっかで閉じてる？

以上4点を踏まえ、javaScriptのコードを修正しました。

2020-02-04 00:54 UTC, W-Nakayama-24 commented
>プルリクの分け方のせいかもしれないけど、ファイルをもっているのはサーバ側です。

>jsonファイルって何に使ってます？

CSVとJSONは、レビューにあたってどんな商品データを想定しているかを確認しやすくする目的で併せてプッシュしていました。

確かにクライアント側にこの2つを置いて使っているわけではないので、後ほど削除します。

2020-02-04 01:26 UTC, W-Nakayama-24 commented on client/index.html
> +    </span>
機能仕様書ではメッセージ領域の位置を以下のように定めていました。
- 「検索」ボタンと「購入へ進む」ボタンの間
-   商品名検索フォームの右隣

現在は、以下のように実装しています。
- 「購入へ進む」ボタンの下
- 右寄せ
[参考画像]
![image](https://user-images.githubusercontent.com/54921025/73704815-9e21a580-4737-11ea-8da5-56365d43f76c.png)


>タグの利用や、スタイルシートでwhite-spaceプロパティをnowrapに設定する等の方法を試しましたが仕様書通りの配置が実現しませんでした。

先日の説明が分かりにくくて申し訳なかったですが、
まずは商品名検索フォームの隣に配置するときに改行が挟まってしまう以下のような状態を解消したいです。
![image](https://user-images.githubusercontent.com/54921025/73704876-c90bf980-4737-11ea-9947-5dd36cdced2c.png)

2020-02-04 02:43 UTC, W-Nakayama-24 commented on client/index.js
> +                        j++
- 変数jを削除し、iとkの2つで同じループを再現しました。



- 以下のレビューについて口頭でも詳細を伺いましたが、頂いたアドバイスを2つの関数に反映させました
  >const product = data || {} とかで良さそうに見えます

https://github.com/W-Nakayama-24/ojt_ecsite/pull/6/commits/1a8d629f61205892f5b40babe6445c4a718cec9c

2020-02-04 03:48 UTC, tatsuyaagawa commented on client/index.js
> +                    for (; k < (product.length); k++) {
ごめんなさい。伝え方が悪かったです。
口頭でも話したけど、ここは修正前のままでよくてfor文の中の今 `product' + k` となっているところをiとkで表すと良いかなと思ってコメントしました

2020-02-04 04:06 UTC, W-Nakayama-24 commented on client/index.js
> +                    for (; k < (product.length); k++) {
```
for (var j = 0; j < cols; j++) {
$('.productInfoRow' + i + '').append('<td class="product' + (i * cols + j) + '"></td>');
```

もう一度修正して、コミットしました。いかがでしょうか?
(これだとcolsも使っているので、iとkだけで表現したとは言えないかもしれませんが。。)
https://github.com/W-Nakayama-24/ojt_ecsite/pull/6/commits/28e507e57fd46847ab636cab46b403f5109e4b8c

2020-02-04 04:09 UTC, tatsuyaagawa commented on client/index.js
> +                    for (; k < (product.length); k++) {
良いと思います
colsは使ってて大丈夫です。そこも伝えないといけませんでしたね。。すみません。

2020-02-04 04:58 UTC, W-Nakayama-24 commented
>これはwantでいいのだけど、システムを作っている段階でIPをハードコーディングしてしまうと評価が終わった後お客様のところへ導入するときに変更が必要になって色々アレなんです。

>見やすくそろえているというのはとてもいいのだけど、もしエラー用のclassがmessageじゃなくなったら変更するところは・・・と考えるとリファクタリングの余地があるかもね

以上2点をふまえソースコードを修正しました。

2020-02-04 05:03 UTC, iwanam commented on client/index.html
> +    </span>
こんな風に配置すればいいんでねが

![image](https://user-images.githubusercontent.com/24929381/73715340-0469f080-4757-11ea-86a3-694a12e47fa6.png)

2020-02-04 05:43 UTC, tatsuyaagawa commented on client/index.js
> +    name = name || {};
こっちはnameはstringを期待しているので `name || ""` じゃないとsliceでエラーになりそう

2020-02-04 05:48 UTC, W-Nakayama-24 commented on client/index.js
> +    name = name || {};
ありがとうございます、修正しました。

2020-02-04 06:30 UTC, W-Nakayama-24 commented on client/index.html
> +    </span>
見せていただいた画像を参考に以下の手法を探し出し、採用しました。
- htmlの<div>タグを使った要素の分割
- cssのdisplayプロパティ-tableを使ったレイアウトの調整

機能仕様書で定めたレイアウトが再現できました。
![image](https://user-images.githubusercontent.com/54921025/73719370-96c3c180-4762-11ea-9393-0db15407d758.png)

2020-02-04 06:33 UTC, tatsuyaagawa approved these changes

2020-02-04 06:37 UTC, SaitohYuusuke approved these changes

2020-02-04 06:39 UTC, iwanam approved these changes

2020-02-04 07:03 UTC, merged