【OJT課題 ECサイトの作成】テストコード UC02[商品を購入する]部分
W-Nakayama-24/ojt_ecsite pull request #9
Opened 2020-02-13 06:43 UTC by W-Nakayama-24

2020-02-14 00:40 UTC, iwanam commented
テストファーストでやるのはいいのだけど、実装と一緒にレビューに出した方がいいような気がする。
実際に単体テストコードだけをレビューすることはあまりないですな。(ホワイトボックスにならないので）
テスト仕様書とか、機能テストの場合は単品でレビューするけどね。

2020-02-14 00:44 UTC, W-Nakayama-24 commented
>テストファーストでやるのはいいのだけど、実装と一緒にレビューに出した方がいいような気がする。
実際に単体テストコードだけをレビューすることはあまりないですな。(ホワイトボックスにならないので）
テスト仕様書とか、機能テストの場合は単品でレビューするけどね。

なるほど、そうなんですね。。。
確かにどんなソースコードを実装して単体テストを通過しているのか伝わっていた方が良いですね
後ほどソースコードもプルリクエストを出します。

2020-02-14 02:24 UTC, W-Nakayama-24 commented
単体テストのカバレッジを記載します

**ProductDataCollectorクラス**
![image](https://user-images.githubusercontent.com/54921025/74495861-4e539300-4f1c-11ea-9076-63b7ff550469.png)


**TotalPriceCalculatorクラス**
![image](https://user-images.githubusercontent.com/54921025/74495882-5e6b7280-4f1c-11ea-86bd-7ca93e01ed24.png)


**Receiptクラス**
![image](https://user-images.githubusercontent.com/54921025/74495902-704d1580-4f1c-11ea-841d-0d52d8d7975e.png)

2020-02-14 04:08 UTC, SeigoKawamura commented on test/ProductDataCollectorTest.java
> +        assertThat(result, is(expected));
Listの要素数、値や順序が正しいことを確認するメソッドがあるみたいです。
http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/Matchers.html#contains(E...)

2020-02-14 04:08 UTC, SeigoKawamura commented on test/ProductDataCollectorTest.java
> +        assertThat(result, is(not(expected)));
期待する結果は商品IDが3と2の商品のみが返ることなので、それ以外の商品が返らないことも確認するべきだと思います。

2020-02-14 04:08 UTC, SeigoKawamura commented on test/ProductDataCollectorTest.java
> +    @Test(expected = NullPointerException.class)
NullPointerExceptionは最終的にどこでキャッチされるのでしょうか？

2020-02-14 04:08 UTC, SeigoKawamura commented on test/ProductDataCollectorTest.java
> +        String[] requestProductID = null;
`商品のIDにnullが含まれているとき` と、requestProductID自体がnullの場合は別の話ではないですか？

2020-02-14 04:08 UTC, SeigoKawamura commented on test/ProductDataCollectorTest.java
> +     * 購入したい商品のIDとして3,1,2を指定したとき,対応する商品が指定した順番で入ったList<Product>が返却される.
requestProductIDが重複する場合はどうなりますか？

2020-02-14 04:36 UTC, tamikura commented on test/TotalPriceCalculatorTest.java
> +    }
他にも一部がnullだったり、一部がマイナスだったりした場合もあります

2020-02-14 04:40 UTC, tamikura commented on src/ProductDataCollector.java
> +    public static List<Product> collectProductData(String[] checkValues) {
変数に「check」「value」は使わないほうがよいです（WANT）
- 「check＝チェックボックス」から取ってきたと思いますが、それは手段の話で、「選択した＝selected」のほうがよい
   - checkだと妥当性のほうと勘違いされる
- 「value＝値」、全ての変数は値なので、この命名に何の意味もない（あっても無くても同じ）

2020-02-14 04:59 UTC, W-Nakayama-24 commented on test/ProductDataCollectorTest.java
> +        assertThat(result, is(expected));
containsメソッドとemptyメソッドを採用して、不要なコードを削りました。
(研修でjUnit4を入れたときに付属していたCoreMatchersしか使ってこなかったので、新しくMatchersを導入するきっかけになりました)

2020-02-14 05:29 UTC, iwanam requested changes

2020-02-14 05:29 UTC, iwanam commented on src/ProductDataCollector.java
> +        ProductDataCollector.allProductList = allProductList;
この形は変ですな。
staticフィールドに値をセットする役目でしかないのだけど、そのためにnewされたオブジェクトは利用価値がないものになっちゃうから。

2020-02-14 05:29 UTC, iwanam commented on src/ProductDataCollector.java
> +                    purchasedProductList.add(allProductList.get(j));
このロジックはあまりよろしくないかな。
多分やりたいこととしては、△番の商品くれって言われたら、商品リストを順番に見ていってその商品を抽出しているんだろうと思うけど、これだとamazonみたいに数百万商品あったりすると、購入するものの数だけ掛け算になってしまう。
こういうときはMapを使うといいよ

2020-02-14 05:29 UTC, iwanam commented on src/ProductDataCollector.java
> +                int collationID = allProductList.get(j).getProductID();
この書き方も間違いではないけど2世代くらい古い書き方で、Javaでいうと1990年代くらいのやりかたですな。
C言語ではこの書き方になっちゃうけどね。
無理はしなくていいけど、forEachでラムダ式をつかえるようにするといいね。
ちなみにJSでもforEachは使えます。ラムダ式はないけど

2020-02-14 05:29 UTC, iwanam commented on src/Receipt.java
> +    Receipt(String purchasedDateTime, List<Product> purchasedProductList, int TotalPriceExcludeTax,
この書き方だとコンストラクタがパッケージプライベートだけど、何か意識してこう書いた？
アクセス修飾子についてもそろそろ覚えてもいいかもしれないね。(かなり優先度の低いwant）

2020-02-14 05:33 UTC, iwanam commented on src/ProductDataCollector.java
> +                    purchasedProductList.add(allProductList.get(j));
ループの回数はなるべく最小限にする、というのとループの中で不要な処理やnewを呼ばない、という観点はミスりやすくもあり、システムに影響を与えることも多いのでよくチェックされます

2020-02-18 01:59 UTC, W-Nakayama-24 commented on src/ProductDataCollector.java
> +                    purchasedProductList.add(allProductList.get(j));
Mapを使って効率良く探し出すロジックに改善しました。https://github.com/W-Nakayama-24/ojt_ecsite/pull/9/commits/cd05ed111ed70543c3bfa22925fa6feb3f9812c2
暫定の対応として、今あるallProductListを**allProductMap(キーにproductID、値にproductオブジェクト)**へ変換する処理を設けてありますが
他で頂いている指摘も踏まえ、追って修正していきます

2020-02-18 05:04 UTC, W-Nakayama-24 commented on src/ProductDataCollector.java
> +        ProductDataCollector.allProductList = allProductList;
「セッションオブジェクトを取得したBuyProductServletから、商品情報コレクタークラスのstaticフィールドに代入する処理」に変更しました。https://github.com/W-Nakayama-24/ojt_ecsite/pull/9/commits/01bffcaedd7b36e5ab4ff6e6541d584cb1f03582

2020-02-19 00:47 UTC, W-Nakayama-24 commented on test/ProductDataCollectorTest.java
> +        assertThat(result, is(expected));
**[2/19 追記]**
Eclipseにて、「プロジェクト>プロパティ>javaのビルドパス>順序とエクスポート」と画面を移ってhamcrest-1.3-core.jar及びhamcrest-1.3-library.jarのビルドパスをjUnitライブラリより上に設定したところ、解決しました。
Matchersで提供されている検証メソッドを採用します。

2020-02-19 01:24 UTC, W-Nakayama-24 commented
memo
コミットメッセージが逆になっていたので修正したいが、
`git commit --amend`
` git rebase -i HEAD`
が実行できない。

hint: Waiting for your editor to close the file... code C:/Users/~~~/ojt_ecsite/.git/rebase-merge/git-rebase-todo: -c: line 0: unexpected EOF while looking for matching `''
code C:/Users/~~~/ojt_ecsite/.git/rebase-merge/git-rebase-todo: -c: line 1: syntax error: unexpected end of file        
error: There was a problem with the editor ''code'.

2020-02-19 04:15 UTC, W-Nakayama-24 commented on test/ProductDataCollectorTest.java
> +     * 購入したい商品のIDとして3,1,2を指定したとき,対応する商品が指定した順番で入ったList<Product>が返却される.
```
String[] requestProductID = {"1","3","3"};

ProductDataCollector.setAllProductList(allProductList);
List<Product> result = ProductDataCollector.collectProductData(requestProductID);
assertThat(result, is(contains(productForTest1, productForTest3, productForTest3)));
assertThat(result.size(), is(3));
```

重複している分も、そのままList<Product>に格納されることを想定します。
テストケースを追加しました。

2020-02-19 04:19 UTC, W-Nakayama-24 commented on test/ProductDataCollectorTest.java
> +        String[] requestProductID = null;
その通りですね。。。
以下2つのテストケースに分割しました。
- String[] requestProductID の一部の要素にnullが含まれている場合
- String[] requestProductID そのものがnullである場合

※
getParameterValuesでクライアント側からチェックボックスの値を取得しているため、requestProductIDのみString型の配列で取り扱っていますが、
商品IDは元々int型で管理しているため、「商品のIDにnullが含まれているとき」はテストケースから除外しました

2020-02-19 04:36 UTC, W-Nakayama-24 commented on test/ProductDataCollectorTest.java
> +    @Test(expected = NullPointerException.class)
ユースケース01と同様に、単体テストで発生しうる例外のcatch句をサーブレットに追加しました。

発生した例外について対処方法/原因がシステム利用者にも伝わることが理想的ですが、それらを考慮した実装へ改善することはwant要件としました。

https://github.com/W-Nakayama-24/ojt_ecsite/pull/9/commits/45034b8996ee3b632c8f98a27029a3f32c8e849c

2020-02-19 04:56 UTC, W-Nakayama-24 commented on test/TotalPriceCalculatorTest.java
> +    }
ご指摘ありがとうございます、テストケースを追加しました。
https://github.com/W-Nakayama-24/ojt_ecsite/pull/9/commits/87c6c8ac73cdbac50c30af602d140af15b7f38c6
https://github.com/W-Nakayama-24/ojt_ecsite/pull/9/commits/a89ae2a81af4fb118903a2b81d60eb214becc9e9

2020-02-19 05:29 UTC, W-Nakayama-24 commented
単体テストのカバレッジを記載します

**ProductDataCollector**

![image](https://user-images.githubusercontent.com/54921025/74804613-12f20380-5324-11ea-8da0-8a5db9e30af4.png)

**TotalPriceCalculator**

![image](https://user-images.githubusercontent.com/54921025/74804545-e2aa6500-5323-11ea-9330-9512ffdfffbc.png)

**Receipt**

![image](https://user-images.githubusercontent.com/54921025/74804529-d45c4900-5323-11ea-8411-bd5bdd66ebe7.png)

2020-02-19 06:57 UTC, W-Nakayama-24 commented on src/ProductDataCollector.java
> +    public static List<Product> collectProductData(String[] checkValues) {
過去に一度教えていただいた観点でしたね、失礼しました。
命名を修正しました。https://github.com/W-Nakayama-24/ojt_ecsite/pull/9/commits/93d3bd1fa806602aa453c01795e80d0a69093ff5

(SelectedId"Array" に関して、Arrayが必要かどうか迷いましたが拡張for文における可読性を優先してこの命名としました)

2020-02-19 07:21 UTC, W-Nakayama-24 commented on src/ProductDataCollector.java
> +                int collationID = allProductList.get(j).getProductID();
18日に少し調べてから、分かる範囲でラムダ式・拡張for文に書き換えました。 

   public static List<Product> collectProductData(String[] selectedIdArray) {

        // リクエストに対応する商品を探す処理を効率化するため,staticフィールドにセットされているListをMapに変換
        Map<Integer, Product> allProductMap = new HashMap<>();
        allProductMap = allProductList.stream().collect(
                Collectors.toMap(allProductList -> allProductList.getProductID(), allProductList -> allProductList));

        // リクエストに対応する商品を探し出し,リストに格納してから返却する.
        List<Product> purchasedProductList = new ArrayList<>();
        for (String selectedId : selectedIdArray) {
            Product getResult = allProductMap.get(Integer.parseInt(selectedId));
            if(getResult != null) purchasedProductList.add(getResult);
        }
        return purchasedProductList;
    }

2020-02-19 07:24 UTC, SeigoKawamura commented on test/ProductDataCollectorTest.java
> +    @Test(expected = NullPointerException.class)
https://github.com/W-Nakayama-24/ojt_ecsite/pull/9/files#diff-fac0946ce97e2c41fa541bb9b5682b86R30
↑collectProductDataメソッドが呼ばれる箇所はmakeReceiptの中ですよね？

https://github.com/W-Nakayama-24/ojt_ecsite/pull/9/files#diff-7644fa9960b23588a369cd8c17b26647R44
↑そして、makeReceiptメソッドは上記で呼ばれているので、例外がキャッチされずに異常終了してしまいます。

2020-02-19 07:40 UTC, W-Nakayama-24 commented on test/ProductDataCollectorTest.java
> +    @Test(expected = NullPointerException.class)
https://github.com/W-Nakayama-24/ojt_ecsite/pull/9/commits/562fe8adbec995299ffad5d71c515d8cdd964cff

catch句だけ追加して完了させた気になっていました、失礼しました。。。
try~catch文の範囲を修正し、BuyProductSevletでわざと例外を発生させる処理を入れたとき正常にキャッチされることを確認してからコミットしました

2020-02-19 07:53 UTC, SeigoKawamura approved these changes

2020-02-20 03:51 UTC, iwanam requested changes

2020-02-20 03:51 UTC, iwanam commented on src/ProductDataCollector.java
> +                purchasedProductList.add(getResult);
中かっこ省略はC言語では当たり前なんだけど、Javaでは禁忌
処理を追加する場合にバグを生みやすくなるので

2020-02-20 03:51 UTC, iwanam commented on src/ProductDataCollector.java
> +                Collectors.toMap(allProductList -> allProductList.getProductID(), allProductList -> allProductList));
すげー頑張ったねえ。↓くらいでいいかなと思っていたんだけど勉強になったのはよかった
 `list.forEach(data -> map.put(data.getId(), data));`

2020-02-20 04:54 UTC, W-Nakayama-24 commented on src/ProductDataCollector.java
> +                purchasedProductList.add(getResult);
修正しました。以後気をつけます。https://github.com/W-Nakayama-24/ojt_ecsite/pull/9/commits/979b5180888f545391735dd55fe77a92cc465d17

2020-02-20 04:56 UTC, W-Nakayama-24 commented on src/ProductDataCollector.java
> +        allProductList.forEach(product -> allProductMap.put(product.getProductID(), product));
>すげー頑張ったねえ。↓くらいでいいかなと思っていたんだけど勉強になったのはよかった
`list.forEach(data -> map.put(data.getId(), data));`

折角なので紹介してくださったforEach文を使って、正常な動作・単体テスト通過を確認しました。
難しく考えすぎたかもしれませんね。。。次回ユースケースで機会があればStreamAPIも活用したいと思います

2020-02-20 05:06 UTC, W-Nakayama-24 commented
単体テストのカバレッジを記載します

**ProductDataCollector**


![image](https://user-images.githubusercontent.com/54921025/74902653-046e1f80-53ea-11ea-884d-7614989ac768.png)

**TotalPriceCalculator**

![image](https://user-images.githubusercontent.com/54921025/74902683-21a2ee00-53ea-11ea-8a0c-e7c1349eac38.png)


**Receipt**

![image](https://user-images.githubusercontent.com/54921025/74902707-32536400-53ea-11ea-900f-495b718654a1.png)

2020-02-20 05:22 UTC, iwanam approved these changes
どちらが分かりやすいかっていうのと、適材適所ってやつだね。たとえばリストからフィルタリングしたいとかだとStreamのがいいかもしれないし、例えば自分のクラスにPredicateを実装してうまく使うとかね。
JUnitがちゃんとかけていれば、今回みたいに実装内容を変更してもテストぽちっとするだけで大丈夫かわかるっていうのが自動テストの醍醐味

2020-02-20 05:50 UTC, tamikura approved these changes

2020-02-20 06:14 UTC, merged